Либерия
SierraBay/SierraBay12 pull request #103
Opened 2023-03-09 16:23 UTC by LordNest

Данный Пулл Реквест добавляет FTV Liberia, торговое судно Вольного Торгового Союза

Closes #49 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена авей-карта "Либерия"
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2023-03-12 14:59 UTC, SuhEugene commented
Какой ревью... Оно тесты даже не проходит...

2023-03-25 14:07 UTC, SuhEugene requested changes
![https://cdn.discordapp.com/emojis/896477408339849227.png?size=32](UwUThinking)

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +/datum/job/submap/merchant
`/datum/job/submap/merchant` -> `/datum/job/submap/merchant_leader`
`/datum/job/submap/merchant_trainee` -> `/datum/job/submap/merchant`
Чтобы жобка сабмапы соответствовала аутфиту
Некрасиво же

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +		SKILL_PILOT	  = SKILL_BASIC
А давай либо сверху тоже таб будет, либо здесь вместо таба - три пробела...

```suggestion
		SKILL_PILOT   = SKILL_BASIC
```

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +	latejoin_at_spawnpoints = 1
Були - `TRUE`/`FALSE`

```suggestion
	latejoin_at_spawnpoints = TRUE
```

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +	create_record = 0
Були - `TRUE`/`FALSE`

```suggestion
	create_record = FALSE
```

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +	create_record = 0
Були

```suggestion
	create_record = FALSE
```

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +	latejoin_at_spawnpoints = 1
```suggestion
	latejoin_at_spawnpoints = TRUE
```

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +		new /obj/item/spacecash/bundle/c2500 (sec_briefcase)
```suggestion
		new /obj/item/spacecash/bundle/c2500(sec_briefcase)
```

Просто чтоб по фен-шую

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +	for(var/i=money_to_put, i>0, i--)
```suggestion
	for(var/i = money_to_put, i > 0, i--)
```
Фен-Шуй требует чтобы кровать стояла головой на север *вроде бы*.

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +//	pda_type = /obj/item/modular_computer/pda
```suggestion
```

TODO нема, значит комментарий не нужен

2023-03-25 14:07 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> +	economic_power = 10 // We use splitted from station account system, which need lover economic_power to not break things
Это проценты?
Если да, то это выглядит как кринжа какая-то...

2023-03-25 14:10 UTC, LordNest commented on mods/maps/liberia/liberia_jobs.dm
> +	economic_power = 10 // We use splitted from station account system, which need lover economic_power to not break things
Это не проценты, это статичное значение, не процентное.

2023-03-26 07:05 UTC, SuhEugene approved these changes
Галка

2023-03-26 07:16 UTC, merged