Cuddle Bug Fixes
SierraBay/SierraBay12 pull request #113
Opened 2023-03-18 09:33 UTC by cuddleandtea

1. Фикс ошибки кода при граб моба -> помещении на стол. В VS был конфликт, теперь функция работает правильно и удалённый граб не создаёт ошибку, а продолжает действие.

2. [Ишью](https://github.com/SierraBay/SierraBay12/issues/112)

<details>
<summary>Чейнджлог</summary>

```yml

tweak: Добавлена проверка на удалённый граб

```

</details>

Далее честно заполняем галочки. Чем больше галочек, тем быстрее проверять Pull Request, соответственно он быстрее будет принят. Чтобы отметить - ставим `x` (икс) внутри квадратных скобочек вот так: `- [x] ...`. Галочки можно доставлять позже по мере окончания работы над PR'ом. ЭТОТ ПУНКТ НУЖНО УДАЛИТЬ.

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2023-03-18 21:13 UTC, SuhEugene requested changes
Мод - добавление нового контента скорее, чем фиксы старого. Реализация правильная, идея понята неправильно. Прошу всё это засунуть в пак фиксов - `/packs/sierra-tweaks/`

Структура очень похожая, думаю, разобраться будет несложно.

2023-03-23 03:59 UTC, SuhEugene requested changes
Тут пути попроще, чем как было у инфинити потому что почему бы и да:
- `/packs/sierra-tweaks/code/game/objects/buckling.dm` -> `/packs/sierra-tweaks/objects/buckling.dm`
- `/packs/sierra-tweaks/code/modules/mob/grab/grab_object.dm` -> `/packs/sierra-tweaks/mob/grab/grab_object.dm`

2023-03-23 11:48 UTC, cuddleandtea commented
> Тут пути попроще, чем как было у инфинити потому что почему бы и да:
> 
> * `/packs/sierra-tweaks/code/game/objects/buckling.dm` -> `/packs/sierra-tweaks/objects/buckling.dm`
> * `/packs/sierra-tweaks/code/modules/mob/grab/grab_object.dm` -> `/packs/sierra-tweaks/mob/grab/grab_object.dm`

Я не понимаю...а зачем сокращать путь кода?

2023-03-24 13:28 UTC, SuhEugene commented
> > Тут пути попроще, чем как было у инфинити потому что почему бы и да:
> > 
> > * `/packs/sierra-tweaks/code/game/objects/buckling.dm` -> `/packs/sierra-tweaks/objects/buckling.dm`
> > * `/packs/sierra-tweaks/code/modules/mob/grab/grab_object.dm` -> `/packs/sierra-tweaks/mob/grab/grab_object.dm`
> 
> Я не понимаю...а зачем сокращать путь кода? Я могу исправить, но так же более полноценно ветвиться изменение и не стакается всё в одну кучу

Может и ветвится, но таким образом проще и `#include` писать, и видеть всё это дело, и по файлам бегать. Может в долгосрочной перспективе это и не лучшая практика, но ты вдохновил меня на некоторый рефактор этого всего дела и скоро я слегка поменяю идейную структуру.

2023-03-24 13:45 UTC, SuhEugene requested changes

2023-03-24 13:45 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/objects/buckling.dm
Скорее всего это можно сделать в разы проще:
```dm
/obj/buckle_mob(mob/living/M)
	. = ..()
	if (.)
		M.pixel_x = initial(M.pixel_x)
		M.pixel_y = initial(M.pixel_y)
```

2023-03-24 13:45 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/objects/buckling.dm
> +	M.pixel_y = initial(pixel_y)
Нужно брать изначальные `pixel_x` и `pixel_y` у моба, а не у объекта, на который моб садится
```suggestion
	M.pixel_x = initial(M.pixel_x)
	M.pixel_y = initial(M.pixel_y)
```

2023-03-24 13:45 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/objects/buckling.dm
Это решение, конечно, стоит проверить, но скорее всего оно сработает

2023-03-24 13:45 UTC, SuhEugene commented on packs/sierra-tweaks/code/modules/mob/grab/grab_object.dm
Большая умная конструкция, а потому хочу в коркоде видеть это, пожавуйста... ![image](https://user-images.githubusercontent.com/32931701/227537719-e895d77a-ef97-4004-bd0b-3ccdfa0c959f.png)

```dm
	if (A.use_grab(src, user, click_params))
		// [SIERRA]
		if (QDELETED(src))
			return TRUE
		// [/SIERRA]
		assailant.setClickCooldown(DEFAULT_ATTACK_COOLDOWN)

2023-03-26 06:37 UTC, LordNest approved these changes

2023-03-26 11:19 UTC, cuddleandtea commented on packs/sierra-tweaks/code/game/objects/buckling.dm
> +	M.pixel_y = initial(pixel_y)
Да, оно так работает. Но если фурнитура будет сдвинута по осям, то моб будет сидеть не на объекте, а в "стандартной точке"

2023-03-26 11:30 UTC, SuhEugene approved these changes
![image](https://user-images.githubusercontent.com/32931701/227772724-1b10c339-46a8-4fc1-b8df-c2748cbe77c9.png)

2023-03-26 11:31 UTC, SuhEugene approved these changes
![image](https://user-images.githubusercontent.com/32931701/227772764-7374f136-e0de-4c79-a384-1a8b05cc8a4b.png)

2023-03-26 14:24 UTC, merged