FEAT: Background editor translation, additional backgrounds
SierraBay/SierraBay12 pull request #1442
Opened 2023-11-06 09:52 UTC by UEDCommander

Редактор бэкграунда персонажей полностью переведен, включая все культуры, происхождения, религии и фракции, существующие на SierraBay и в соседствующих модах;
Для людей, унати и скреллов добавлены культуры, происхождения и фракции, что были доступны для них на Infinity, но не имелись в наличии на SierraBay;
Добавлены языки, соответствующие новым культурам - мирраниский, авалонский, лорриманский.

close #1438 
close #1284 

### Чейнджлог
```yml
🆑uedhighcommand
tweak: Полностью переведен редактор бэкграунда персонажа
rscadd: Перенесены культуры, места проживания и фракции с Infinity
rscadd: Добавлены новые языки: мирраниский, авалонский, лорриманский
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2023-11-12 16:01 UTC, SuhEugene requested changes

2023-11-12 16:01 UTC, SuhEugene commented on code/__defines/culture.dm
> +// [SIERRA-EDIT]
Оригинальное должно тоже остаться с отметкой `// SIERRA-EDIT - ORIGINAL`

2023-11-12 16:01 UTC, SuhEugene commented on code/__defines/~mods/culture.dm
Это б объединить с `code/__defines/~mods/language.dm` и сунуть в `code/__defines/~mods/expanded_culture_descriptor.dm`

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/01_culture.dm
> +// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Сокращение html-строки для нормальной работы переопределения get_description; перевод буков
```suggestion
		// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Сокращение html-строки для нормальной работы переопределения get_description; перевод буков
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/01_culture.dm
> +// [SIERRA-EDIT]
```suggestion
		// [SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/01_culture.dm
> +// [SIERRA-EDIT]
```suggestion
				// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Изменение схемы получения названия культуры, чтобы поддерживать возможность их перевода без переработки всей сабсистемы культур
				// if (pref.cultural_info[token] == V) // SIERRA-EDIT - ORIGINAL
				// 	. += "[SPAN_CLASS("linkOn", "[V]")] " // SIERRA-EDIT - ORIGINAL
				// else // SIERRA-EDIT - ORIGINAL
				// 	. += "<a href='?src=\ref[src];set_token_entry_[token]=[sanitized_value]'>[V]</a> " // SIERRA-EDIT - ORIGINAL
				var/singleton/cultural_info/VCulture = SSculture.get_culture(V)
				if(VCulture)
					if (pref.cultural_info[token] == V)
						. += "[SPAN_CLASS("linkOn", "[VCulture.get_nickname()]")] "
					else
						. += "<a href='?src=\ref[src];set_token_entry_[token]=[sanitized_value]'>[VCulture.get_nickname()]</a> "
				// [SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/01_culture.dm
> +		var/append_text = "<a href='?src=\ref[src];toggle_verbose_[token]=1'>[hidden[token] ? "Расширить" : "Скрыть"]</a>"
Поменял две строчки посередине местами и `[SIERRA-EDIT] - ORIGINAL` заменил на `SIERRA-EDIT - ORIGINAL` - как в доках.
```suggestion
		//var/title = "<a href='?src=\ref[src];expand_options_[token]=1'>[tokens[token]]</a><b>- </b>[pref.cultural_info[token]]" // SIERRA-EDIT - ORIGINAL
		//var/append_text = "<a href='?src=\ref[src];toggle_verbose_[token]=1'>[hidden[token] ? "Expand" : "Collapse"]</a>" // SIERRA-EDIT - ORIGINAL
		var/title = "<a href='?src=\ref[src];expand_options_[token]=1'>[tokens[token]]</a><b>- </b>"
		var/append_text = "<a href='?src=\ref[src];toggle_verbose_[token]=1'>[hidden[token] ? "Расширить" : "Скрыть"]</a>"
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/02_language.dm
> +	//. += "<b>Languages</b><br>" // [SIERRA-EDIT] - ORIGINAL
```suggestion
	// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Перевод
	// . += "<b>Languages</b><br>" // SIERRA-EDIT - ORIGINAL
	. += "<b>Языки</b><br>"
	// [/SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/02_language.dm
> +		//. += "Your current species, faction or home system selection does not allow you to choose additional languages.<br>" // [SIERRA-EDIT] - ORIGINAL
```suggestion
		// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Перевод
		// . += "Your current species, faction or home system selection does not allow you to choose additional languages.<br>" // SIERRA-EDIT - ORIGINAL
		. += "Ваша фракция, раса или место проживания не позволяют вам выбрать дополнительные языки.<br>"
		// [/SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/02_language.dm
> +			//alert(user, "You have already selected the maximum number of languages!") // [SIERRA-EDIT] - ORIGINAL
```suggestion
			// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Перевод
			// alert(user, "You have already selected the maximum number of languages!") // SIERRA-EDIT - ORIGINAL
			alert(user, "Вы уже выбрали максимальное количество языков!")
			// [/SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/02_language.dm
> +			//alert(user, "There are no additional languages available to select.") // [SIERRA-EDIT] - ORIGINAL
```suggestion
			// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Перевод
			// alert(user, "There are no additional languages available to select.") // SIERRA-EDIT - ORIGINAL
			alert(user, "Вы уже выбрали все доступные языки.")
			// [/SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/02_language.dm
> +			//var/new_lang = input(user, "Select an additional language", "Character Generation", null) as null|anything in available_languages // [SIERRA-EDIT] - ORIGINAL
```suggestion
			// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Перевод
			// var/new_lang = input(user, "Select an additional language", "Character Generation", null) as null|anything in available_languages // SIERRA-EDIT - ORIGINAL
			var/new_lang = input(user, "Выберите дополнительный язык", "Character Generation", null) as null|anything in available_languages
			// [/SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/02_language.dm
> +		//LAZYADD(., "- <a href='?src=\ref[src];add_language=1'>add</a> ([remaining_langs] remaining)<br>") // [SIERRA-EDIT] - ORIGINAL
Аналогично тому, что выше:
- Пробел после `//`
- Оригинал перед изменением
- Открывающий-закрывающий теги `[SIERRA-EDIT]` на новой линии

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/client/preference_setup/background/03_records.dm
Аналогично тому, что выше:
- Пробел после `//`
- Оригинал перед изменением
- Открывающий-закрывающий теги `[SIERRA-EDIT]` на новой линии

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Перевод здесь, потому что переопределение в мастер файлах ломает hidden_valid_jobs. Увы.
```suggestion
	// [SIERRA-EDIT] - EXPANDED_CULTURE_DESCRIPTOR - Перевод здесь, потому что переопределение в мастер файлах ломает hidden_valid_jobs. Увы.
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +// [SIERRA-EDIT]
```suggestion
	// [SIERRA-EDIT]
```

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +	var/grade = copytext("[name]",7)
А зачем это надо? В чём проблема? И почему не `copytext_char`?

2023-11-12 16:01 UTC, SuhEugene commented on code/modules/culture_descriptor/location/_location.dm
Аналогично тому, что выше:
- Пробел после `//`
- Оригинал перед изменением
- Открывающий-закрывающий теги `[SIERRA-EDIT]` на новой линии

2023-11-12 16:01 UTC, SuhEugene commented on mods/global_modpacks.dm
> +#include "expanded_culture_descriptor/_expanded_culture_descriptor.dme"
Они тут все по алфавиту...

2023-11-12 16:01 UTC, SuhEugene commented on mods/_master_files/code/modules/culture_descriptor/_culture.dm
> +	var/nickname
Это 100% дополнение, а не оверрайд. Дополнения в мод, не сюда.

2023-11-12 16:01 UTC, SuhEugene commented on mods/_master_files/code/modules/culture_descriptor/culture/cultures_adherent.dm
Я просто поверю на слово, что все остальные файлы - оверрайды, а не дополнения

По крайней мере пока что

Если там среди оверрайдов окажутся и дополнения, это может вызывать проблемы в будущем

2023-11-12 16:01 UTC, SuhEugene commented on mods/_master_files/code/modules/species/station/lizard.dm
Вы уверены, что это надо прям оверрайдить, а нельзя дополнить в файле расы? (Аналогичный вопрос к файлам ниже)

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/README.md
> +## Мод-пример
Название мода

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/README.md
> +- `code/__defines/~mods/language.dm`: `LANGUAGE_HUMAN_LORRIMAN`, `LANGUAGE_HUMAN_AVALON`, `LANGUAGE_HUMAN_MIRANIAN`
Обновить после объединения

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/README.md
> +- `mods/_master_files/code/modules/species/station/station.dm`: `/datum/species/human`
Вопрос по этим оверрайдам выше

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/_expanded_culture_descriptor.dm
> +/singleton/modpack/example
Синглтон не переименован

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/_expanded_culture_descriptor.dme
> +// BEGIN_INCLUDE
Клуелесс

```suggestion
```

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/_expanded_culture_descriptor.dme
> +// END_INCLUDE
```suggestion
```

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/code/_culture.dm
Во, вот сюда и вставь объявление `var/nickname` для културал инфо.

Только кто бы ещё объяснил зачем оно вообще надо...

И вообще наверное это можно было бы упростить до `return nickname || name`

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/_expanded_culture_descriptor.dme
> +#include "code\chinese.dm"
Возможно языки стоило бы сунуть в отдельную подпапку или отметить как `language_языкнейм.dm`

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/code/german.dm
> +	 "cker", "Bürs", "te", "ung", "trau", "schöns", "blech", "schwis", "rei", "scho", "zeich", "nen", "nien", "der", "unter", "heil", "ö", "ü", "ß", "ße"
```suggestion
		"sieg", "mensch", "tag", "buch", "haus", "boot", "heu", "te", "ge", "fahr", "lö", "schen", "mee", "re", "el", "er", "was", "ser", "grü", "ße", "kat", "ze",
		"cker", "Bürs", "te", "ung", "trau", "schöns", "blech", "schwis", "rei", "scho", "zeich", "nen", "nien", "der", "unter", "heil", "ö", "ü", "ß", "ße"
```

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/code/cultures_human.dm
> +		LANGUAGE_SIGN)
```suggestion
	secondary_langs = list(
		LANGUAGE_HUMAN_EURO,
		LANGUAGE_HUMAN_CHINESE,
		LANGUAGE_HUMAN_ARABIC,
		LANGUAGE_HUMAN_INDIAN,
		LANGUAGE_HUMAN_IBERIAN,
		LANGUAGE_HUMAN_RUSSIAN,
		LANGUAGE_SPACER,
		LANGUAGE_GUTTER,
		LANGUAGE_SIGN
	)
```

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/code/cultures_human.dm
> +		LANGUAGE_SIGN)
```suggestion
	secondary_langs = list(
		LANGUAGE_HUMAN_EURO,
		LANGUAGE_HUMAN_CHINESE,
		LANGUAGE_HUMAN_ARABIC,
		LANGUAGE_HUMAN_INDIAN,
		LANGUAGE_HUMAN_IBERIAN,
		LANGUAGE_HUMAN_RUSSIAN,
		LANGUAGE_SPACER,
		LANGUAGE_GUTTER,
		LANGUAGE_SIGN
	)
```

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/code/cultures_human.dm
> +		LANGUAGE_SIGN)
```suggestion
	secondary_langs = list(
		LANGUAGE_HUMAN_EURO,
		LANGUAGE_HUMAN_CHINESE,
		LANGUAGE_HUMAN_ARABIC,
		LANGUAGE_HUMAN_INDIAN,
		LANGUAGE_HUMAN_IBERIAN,
		LANGUAGE_HUMAN_RUSSIAN,
		LANGUAGE_SPACER,
		LANGUAGE_GUTTER,
		LANGUAGE_SIGN
	)
```

2023-11-12 16:01 UTC, SuhEugene commented on mods/expanded_culture_descriptor/code/cultures_human.dm
> +		LANGUAGE_SIGN)
```suggestion
	secondary_langs = list(
		LANGUAGE_HUMAN_EURO,
		LANGUAGE_HUMAN_CHINESE,
		LANGUAGE_HUMAN_ARABIC,
		LANGUAGE_HUMAN_INDIAN,
		LANGUAGE_HUMAN_IBERIAN,
		LANGUAGE_HUMAN_RUSSIAN,
		LANGUAGE_SPACER,
		LANGUAGE_GUTTER,
		LANGUAGE_SIGN
	)
```

2023-11-12 17:08 UTC, UEDCommander commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +	var/grade = copytext("[name]",7)
В дефайнах используются названия формата "Grade A", а не просто "A" - либо делать так, либо придется переопределять ещё и дефайны тоже. copytext_char в данном контексте в целом разницы большой не сделает, но можно и его на случай, если кто-то решит делать грейды русскими символами когда-то.

2023-11-12 17:37 UTC, UEDCommander commented on mods/expanded_culture_descriptor/code/_culture.dm
Синглтоны культур используют название в качестве значения, через которое на конкретные экземпляры ссылаются проки - если название состоит из символов юникода, ссылка не будет работать. Это вписано непосредственно в сабсистему, и мне как-то не охота переписывать её ради перевода, поэтому такой костылик.

2023-11-16 07:43 UTC, SuhEugene commented on code/modules/client/preference_setup/background/01_culture.dm
> +		//var/append_text = "<a href='?src=\ref[src];toggle_verbose_[token]=1'>[hidden[token] ? "Expand" : "Collapse"]</a>" // SIERRA-EDIT - ORIGINAL
Тут пробелы забыл...
```suggestion
		// var/title = "<a href='?src=\ref[src];expand_options_[token]=1'>[tokens[token]]</a><b>- </b>[pref.cultural_info[token]]" // SIERRA-EDIT - ORIGINAL
		// var/append_text = "<a href='?src=\ref[src];toggle_verbose_[token]=1'>[hidden[token] ? "Expand" : "Collapse"]</a>" // SIERRA-EDIT - ORIGINAL
```

2023-11-16 07:51 UTC, SuhEugene commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +	var/grade = copytext("[name]",7)
Ну я не знаю на самом деле


>  ...Xynergy в соответствии с классом "Grade A" и пригодны для исполнения обязанностей...

Выглядит не так уж и плохо...
Ну ладно, пусть будет, надеюсь оффы не придумают как сломать это.

Здесь оставить бы какую-нибудь проверку, которая проверяет что слово с "Grade" начинается, и иначе - крашит: `crash_with("Текст ошибки")`. Чтобы если оффы что и поменяли - это было сразу легко заметно.

2023-11-16 07:57 UTC, SuhEugene commented
А ещё из-за Ceti-expansion апдейта оно падает на тестах...

2023-11-16 17:54 UTC, UEDCommander commented
> А ещё из-за Ceti-expansion апдейта оно падает на тестах...
> 
> То что они там понаписали, наверное надо кому-то толкнуть переводить. Если не возьмёшься - пни, я сам поищу на перевод кого-нибудь.

Думаю сделаю, раз уж доработка нужна тут энивей

2023-11-16 18:09 UTC, UEDCommander commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +	var/grade = copytext("[name]",7)
Окей, добавлю

2023-11-16 20:55 UTC, UEDCommander commented on mods/_master_files/code/modules/species/station/lizard.dm
Пробовал так
`/datum/species/human/New()
	. = ..()
	available_cultural_info += list(
		TAG_CULTURE = list(
			CULTURE_HUMAN_AVACOMMON, 
			CULTURE_HUMAN_AVANOBLE,
			CULTURE_HUMAN_LORRIMAN,
			CULTURE_HUMAN_LORDUP,
			CULTURE_HUMAN_LORDLOW,
			CULTURE_HUMAN_MIRANIAN, 
			CULTURE_HUMAN_NYXIAN
		),
		TAG_FACTION = list(
			FACTION_EXPEDITIONARY,
			FACTION_WARD_TAKAHASHI,
			FACTION_GRAYSON,
			FACTION_AERTHER,
			FACTION_MAJOR_BILL,
			FACTION_FOCAL_POINT,
			FACTION_XION,
			FACTION_VEY_MED,
			FACTION_BISHOP,
			FACTION_SEPTENERGO,
			FACTION_ZPCI
		),
		TAG_HOMEWORLD = list(
			HOME_SYSTEM_TERSTEN,
			HOME_SYSTEM_AVALON,
			HOME_SYSTEM_MIRANIA,
			HOME_SYSTEM_NYX_BRINKBURN,
			HOME_SYSTEM_NYX_KALDARK,
			HOME_SYSTEM_NYX_ROANOK,
			HOME_SYSTEM_NYX_YUKLIT,
			HOME_SYSTEM_NYX_CASSER
		)
	)`
Но доступный список просто заменяется новым, из-за чего практический эффект такой же как от оверрайда; если же пытаться в каждый список отдельно вносить, компилятор не видит их как приемлемые переменные. Кажется, все-таки нельзя.

2023-11-16 22:57 UTC, UEDCommander commented on mods/_master_files/code/modules/species/station/lizard.dm
Разве что попробовать сделать дополнительный список, куда вкидывать новые названия... хм

2023-11-17 00:19 UTC, UEDCommander commented on mods/_master_files/code/modules/species/station/lizard.dm
Нашел способ через additional_available_cultural_info

2023-11-23 11:24 UTC, SuhEugene requested changes

2023-11-23 11:24 UTC, SuhEugene commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +		grade = copytext_char("[name]",7)
```suggestion
	if (!findtext_char("[name]", "Grade"))
		crash_with("Не удалось получить класс ГБС для формирования описания - вероятно, были изменены дефайны классов ГБС")
		return
	grade = copytext_char("[name]", 7)
```

2023-11-23 11:24 UTC, SuhEugene commented on code/modules/culture_descriptor/location/_location.dm
> +		. += "<b>Столица:</b> [capital]."
```suggestion
		. += "<b>Столица:</b> [capital]."
```

2023-11-23 11:24 UTC, SuhEugene commented on code/modules/culture_descriptor/location/_location.dm
> +		. += "<b>Принадлежность:</b> [ruling_body]."
Ты какие-то пробелы наставил в конце, они не надо.
```suggestion
		. += "<b>Принадлежность:</b> [ruling_body]."
```

2023-11-23 11:24 UTC, SuhEugene commented on mods/expanded_culture_descriptor/README.md
> +- `mods/_master_files/code/modules/culture_descriptor/_culture.dm`: `/singleton/cultural_info/get_text_details()`, `/singleton/cultural_info/get_description(header, append, verbose = TRUE)`
```suggestion
- `mods/_master_files/code/modules/culture_descriptor/_culture.dm`: `/singleton/cultural_info/get_text_details()`, `/singleton/cultural_info/get_description()`
```

2023-11-23 12:49 UTC, SuhEugene commented on code/modules/culture_descriptor/culture/cultures_serpentid.dm
> +	grade = copytext_char("[name]", 7)
А зачем здесь grade = name тогда инициализирован? achE
```suggestion
	if (!findtext_char("[name]", "Grade"))
		crash_with("Не удалось получить класс ГБС для формирования описания - вероятно, были изменены дефайны классов ГБС")
		return
	var/grade = copytext_char("[name]", 7)
```

2023-11-24 08:18 UTC, SuhEugene approved these changes

2023-11-24 08:36 UTC, merged