Hairs port
SierraBay/SierraBay12 pull request #1500
Opened 2023-11-23 16:58 UTC by KamSurvivor

Порт причесок и бород с авроры, ониксбея, инфинити и наших парадизов.

### Чейнджлог
```yml
🆑Kam_Survivor
bugfix: Фиксит репорты по пропавшим прическам
wip: Иконки не грузятся(
rscadd: Пара десятков "новых" причесок с соседних билдов
imageadd: Спрайты причесок
/🆑
```
- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-11-23 18:07 UTC, KamSurvivor commented
Причесал бороды, чтобы они имели ясное название.

2023-11-23 18:12 UTC, KamSurvivor commented
И накидал иссуи, который должны закрыться после этого.

2023-11-24 12:32 UTC, KamSurvivor commented
Вернул две прически, что отвалились по ходу отбраковки дубликатов.

2023-11-24 14:37 UTC, KamSurvivor commented
![уцсцвфцафафуа](https://github.com/SierraBay/SierraBay12/assets/78528410/c63befee-4eab-4d35-bd71-1e0024be6051)

2023-11-24 14:37 UTC, KamSurvivor commented
Все хорошо, проверил раз на локалке все внесенные изменения. Прически отображаются.

2023-11-24 16:50 UTC, SuhEugene requested changes

2023-11-24 16:50 UTC, SuhEugene commented on mods/hairs_ports/_hairs_ports.dme
> +// BEGIN_INCLUDE
```suggestion
```

2023-11-24 16:50 UTC, SuhEugene commented on mods/hairs_ports/_hairs_ports.dme
> +#include "code\_accessory_hair.dm"
Перенести ДО `#endif`

2023-11-24 16:50 UTC, SuhEugene commented on mods/hairs_ports/_hairs_ports.dme
> +// END_INCLUDE
```suggestion
```

2023-11-24 16:50 UTC, SuhEugene commented on mods/global_modpacks.dm
> +#include "hairs_ports/_hairs_ports.dme"
Тут всё в алфавитном порядке...

2023-11-24 16:57 UTC, KamSurvivor commented on mods/hairs_ports/_hairs_ports.dme
> +#include "code\_accessory_hair.dm"
По какой-то причине, это само вылезло. 
Изначально ставил как ты говорил, но после решил оставить так, как меня заставил бьенд это сделать.

2023-11-24 17:03 UTC, SuhEugene commented on mods/hairs_ports/_hairs_ports.dme
> +// END_INCLUDE
```suggestion
```

2023-11-24 17:07 UTC, SuhEugene approved these changes

2023-11-24 17:14 UTC, merged