Adherent Discharge
SierraBay/SierraBay12 pull request #1653
Opened 2023-12-21 15:51 UTC by Lexanx

Возвращает абилку Адхерентов бить электричеством

close #1424

### Чейнджлог
```yml
🆑Lexanx
rscadd: Возвращена способность Адхерентов бить электричеством
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-12-21 21:21 UTC, SuhEugene requested changes
Нельзя просто взять, обернуть код в `// [SIERRA-ADD]` и сказать что он теперь модульный... Увы.

Подказки как это делать:
- Создать модпак можно двойным щелчком по `CREATE_MOD.py` в папке `mods`. Подробнее читай в [руководстве по модуляризации](https://github.com/SierraBay/SierraBay12/blob/dev-sierra/mods/README.md#%D0%B1%D1%8B%D1%81%D1%82%D1%80%D0%BE%D0%B5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-%D0%BC%D0%BE%D0%B4%D0%B0), там же и другие способы.
- Про то [как правильно размещать код в папке `_master_files`](https://github.com/SierraBay/SierraBay12/blob/dev-sierra/mods/README.md#%D0%BF%D0%B0%D0%BF%D0%BA%D0%B0-_master_files) написано в нём же.

2023-12-21 21:21 UTC, SuhEugene commented on code/_onclick/click.dm
> +		return
Я думаю и здесь надо вызвать родителя.
```suggestion
		return ..()
```

2023-12-21 21:21 UTC, SuhEugene commented on code/modules/organs/internal/species/adherent.dm
> +// [SIERRA-ADD]
В мод

2023-12-21 21:21 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/human_powers.dm
> +// [SIERRA-ADD]
В мод

2023-12-21 21:21 UTC, SuhEugene commented on code/_onclick/click.dm
В `_master_files`

2023-12-21 21:21 UTC, SuhEugene commented on code/modules/species/station/adherent.dm
> +
Это нужно реализовать иначе. Создать в `_master_files` соответствующую папку и там написать что-то типа:
```dm
/datum/species/adherent/New()
	LAZYINITLIST(inherent_verbs)
	inherent_verbs += /mob/living/carbon/human/proc/toggle_emergency_discharge
	..()
```

2024-01-02 01:31 UTC, SuhEugene commented on mods/_master_files/code/_onclick/click.dm
> +		return
```suggestion
		return ..()
```

2024-01-02 01:46 UTC, SuhEugene submitted a review, later dismissed
Отлично. Почти идеально. Остались мелкие недочёты.

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/README.md
> +Твой никнейм
Тут никнейм/имя
```suggestion
Lexanx
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/_master_files/code/_onclick/click.dm
> +		return
Чтоб мод не сломал другие альт-клик абилки на больших дистанциях, если такие появятся, здесь стоит вызвать родителя однозначно
```suggestion
		return ..()
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/code/human_powers.dm
> +// [SIERRA-ADD]
Внутри мода эти комментарии не нужны.
Эти коментарии нужны во всех папках, кроме `mods/`, `maps/sierra/`, `packs/`
```suggestion
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/code/human_powers.dm
> +// [SIERRA-ADD]
Внутри мода эти комментарии не нужны.
Эти коментарии нужны во всех папках, кроме `mods/`, `maps/sierra/`, `packs/`
```suggestion
```

2024-01-02 01:46 UTC, SuhEugene commented on sound/effects/discharge_on.ogg
В мод.
`mods/adherent_discharge/sound/discharge_on.ogg`

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/code/adherent.dm
> +	cell = /obj/item/cell/hyper
Когда добавляешь новую переменную, старые указывать не нужно, они унаследуются
```suggestion
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/code/adherent.dm
> +	// [SIERRA-ADD]
Внутри мода эти комментарии не нужны.
Эти коментарии нужны во всех папках, кроме `mods/`, `maps/sierra/`, `packs/`
```suggestion
	var/ready_to_charge
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/_adherent_discharge.dme
> +#include "code/human_powers.dm"
Может это всё стоит объединить в один файл? И назвать как-нить соответственно. А то human_powers вообще не описывает то что в файле лежит. Внутри мода ты можешь называть файлы как угодно и располагать в них код тоже как вздумается. Ты можешь просто назвать файл `discharge_ability.dm` и засунуть в него код и из `adherent.dm`, и из `human_powers.dm`

Только не забудь сначала из них лишнее удалить. Я там расписал что лишнее.

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/README.md
> +- https://github.com/SierraBay/SierraBay12/pull/#####
```suggestion
- https://github.com/SierraBay/SierraBay12/pull/1653
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/README.md
> +## Мод-пример
```suggestion
## Adherent Discharge
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/_master_files/code/_onclick/click.dm
> +// [SIERRA-ADD]
Внутри мода эти комментарии не нужны.
Эти коментарии нужны во всех папках, кроме `mods/`, `maps/sierra/`, `packs/`
```suggestion
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/_master_files/code/_onclick/click.dm
> +// [SIERRA-ADD]
Внутри мода эти комментарии не нужны.
Эти коментарии нужны во всех папках, кроме `mods/`, `maps/sierra/`, `packs/`
```suggestion
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/_master_files/code/_onclick/click.dm
> +	..()
А вдруг оно чего в будущем возвращать будет
```suggestion
	return ..()
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/_master_files/code/modules/species/station/adherent.dm
> +	..()
Новая строка в конце файла отсутствует. А надо.
```suggestion
	..()

```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/README.md
> +- `code/modules/mob/living.dm`: `proc/overriden_proc`, `var/overriden_var`
```suggestion
- Отсутствуют
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/README.md
> +- `mods/_master_files/code/my_modular_override.dm`: `proc/overriden_proc`, `var/overriden_var`
```suggestion
- `mods/_master_files/code/_onclick/click.dm`: `/mob/living/carbon/human/AltClickOn()`
- `mods/_master_files/code/modules/species/station/adherent.dm`: `/datum/species/adherent/New()`
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/README.md
> +- `code/__defines/~mods/adherent_discharge.dm`: `ADHERENT_DISCHARGE_SPEED_MULTIPLIER`, `ADHERENT_DISCHARGE_SPEED_BASE`
```suggestion
- Отсутствуют
```

2024-01-02 01:46 UTC, SuhEugene commented on mods/adherent_discharge/README.md
> +- `mods/_master_files/icons/obj/alien.dmi`
```suggestion
- Отсутствуют
```

2024-01-07 21:15 UTC, SuhEugene commented
Ещё чуть-чуть... Почти всё идеально...

2024-02-27 15:28 UTC, LordNest approved these changes

2024-02-27 19:59 UTC, merged