Voidsuit & hardsuit Infinity port
SierraBay/SierraBay12 pull request #1717
Opened 2023-12-27 20:00 UTC by UEDCommander

ПР делает что-то умное, а именно - добавляет расовые спрайты, относящиеся к унати, скреллам и таяра, для войдсьютов и ИКС, что присутствовали на инфинити, но отсутствуют на Сьеррабее.

![image](https://github.com/SierraBay/SierraBay12/assets/52104104/036a621a-ae35-4a46-92b9-013498107cb0) ![image](https://github.com/SierraBay/SierraBay12/assets/52104104/5ea1dbb2-1164-4c1a-a4fc-b7c9186f4247) ![image](https://github.com/SierraBay/SierraBay12/assets/52104104/0c0c4d33-fcf9-4a7e-b27e-e8203d74a031)
![image](https://github.com/SierraBay/SierraBay12/assets/52104104/64fdf952-2ad8-4c2b-ba51-515253303e4e) ![image](https://github.com/SierraBay/SierraBay12/assets/52104104/c4e877d5-ca8d-4d76-bb8d-55666f72ee32) ![image](https://github.com/SierraBay/SierraBay12/assets/52104104/cdf66fc4-a684-4a09-86d3-4260099f059a)
![image](https://github.com/SierraBay/SierraBay12/assets/52104104/c599e8b2-6945-4342-a84c-1e657e2848b8) ![image](https://github.com/SierraBay/SierraBay12/assets/52104104/fae8398c-f3fb-484a-a2cb-fb875bf41052)

### Чейнджлог
```yml
🆑UEDHighCommand
imageadd: Портированы расовые спрайты унати, скреллов для большинства войдсьютов
imageadd: Добавлены расовые спрайты унати, скреллов и таяра для ИКС ЛЭКа
rscadd: Унати, скреллы и таяра теперь могут пользоваться ИКС ЛЭКа 
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2023-12-27 20:38 UTC, SuhEugene commented on mods/hardsuits/README.md
> +ID мода: MODPACK_HARDSUITS
```suggestion
ID мода: HARDSUITS
```

2023-12-29 06:23 UTC, SuhEugene requested changes
Хорошо. Сейчас у меня есть только две мелкие правки, но происходящее с `^=` и `|=` меня пугает. Мне явно нужно найти свободное время чтобы хорошенько подумать и понять действительно ли это единственный способ решить задачу.

Решение интересное, но что-то мне подсказывает, что оно не лучшее и даже может навредить.

2023-12-29 06:23 UTC, SuhEugene commented on code/datums/item_modifiers/item_modifier.dm
> +	 // [SIERRA-REMOVE] - MODPACK_HARDSUITS - Поддержка модульного изменения внешнего вида костюмов
```suggestion
	 // [SIERRA-REMOVE] - HARDSUITS - Поддержка модульного изменения внешнего вида костюмов
```

2023-12-29 06:23 UTC, SuhEugene commented on mods/hardsuits/_hardsuits.dme
> +
```suggestion
```

2023-12-29 10:39 UTC, UEDCommander commented
^= и |= решение, конечно, не единственное, но вероятно самое динамичное, которое можно сделать. В случае, если оффы полезут обновлять sprite sheet'ы, только при такой компоновке унатские листы не пострадают.
Есть ещё конечно lazyadd'ы, но судя по тому, что я так и не смог заставить таярский скин на ИКС ЛЭКа, который ими регулируется, работать, они не совсем удачно функционируют.

2024-01-02 16:08 UTC, SuhEugene requested changes
https://discord.com/channels/617003227182792704/923696264523173958/1191773959843225660

2024-01-11 08:38 UTC, LordNest commented
Нужно отметить, что оно закрывает 
 #1316

2024-01-21 17:01 UTC, SuhEugene approved these changes

2024-01-22 16:41 UTC, LordNest approved these changes

2024-01-22 16:48 UTC, merged