FIX: Various issues fix iteration N
SierraBay/SierraBay12 pull request #1773
Opened 2024-01-07 08:52 UTC by LordNest

ПР делает что-то умное

close #1499

### Чейнджлог
```yml
🆑LordNest
bugfix: Пофиксил баг
wip: Добавил что-то, что ещё в процессе
tweak: Подправил что-то
soundadd: Добавил новый звук
sounddel: Удалил старый звук
rscadd: Добавил в игру что-то новое
rscdel: Удалил из игры что-то старое
imageadd: Заменил скреллам глаза на каноничные Чёрные Глаза
maptweak: Отредактировал карту
spellcheck: Исправил опечатку
experiment: Добавил что-то экспериментальное
balance: Заребалансил что-то
admin: Сделал что-то с админскими тулзами
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-01-07 19:56 UTC, SuhEugene commented on maps/sierra/datums/species/species_overrides.dm
> +// Vox
Вох. А про воха забыли

2024-01-07 19:56 UTC, SuhEugene commented on maps/sierra/datums/species/species_overrides.dm
> +Various overrides for standart species, which are too tiny to heve their own mod
```suggestion
Various overrides for standart species, which are too tiny to have their own mod
```

2024-01-07 19:57 UTC, SuhEugene commented on maps/sierra/datums/species/species_overrides.dm
> +	apply_eye_colour = FALSE
Вообще я не думаю что здесь нужно что-то кроме иконки глаз и отмены цвета
```suggestion
	eye_icon = 'maps/sierra/icons/mob/human_races/species/skrell/eyes.dmi'
	apply_eye_colour = FALSE
```

2024-01-07 19:58 UTC, SuhEugene commented on maps/sierra/loadout/loadout_eyes.dm
> +	..()
Почему здесь нельзя просто вот так написать?
```suggestion
/datum/gear/eyes/science
	allowed_roles = RESEARCH_ROLES | EXPLORATION_ROLES
```

2024-01-07 19:58 UTC, SuhEugene commented on maps/sierra/machinery/machinery.dm
> +	icon = 'maps/sierra/icons/obj/shielding.dmi'
А в чём проблема прямой замены переменной?
```suggestion
/obj/machinery/power/shield_generator
	icon = 'maps/sierra/icons/obj/shielding.dmi'
```

2024-01-08 15:04 UTC, LordNest commented on maps/sierra/loadout/loadout_eyes.dm
> +	..()
```/datum/gear/eyes/science/New()
	allowed_roles = RESEARCH_ROLES | EXPLORATION_ROLES
	..()
```
Потому что в maps\torch\loadout\loadout_eyes.dm вот так

2024-01-08 15:10 UTC, LordNest commented on maps/sierra/loadout/loadout_eyes.dm
> +	..()
И да `maps\sierra\loadout\loadout_eyes.dm:2:error: : expected a constant expression`

2024-01-08 18:36 UTC, LordNest commented
```
/obj/machinery/portable_atmospherics/DefaultTopicState()
    return GLOB.physical_state
```
Вот такое машинерии добавить

2024-01-09 03:42 UTC, LordNest commented
И вот это в мод

```js
/mob/living/silicon/ai
    idcard = /obj/item/card/id/sierra/ai

/obj/item/card/id/sierra/ai
    job_access_type = /datum/job/ai

/datum/job/ai/get_access()
    return get_all_station_access()
```

Либо на оффах выдать ИИ `get_all_station_access()`

2024-01-09 19:18 UTC, LordNest commented
> ```
> /obj/machinery/portable_atmospherics/DefaultTopicState()
>     return GLOB.physical_state
> ```
> 
> Вот такое машинерии добавить

А вот не работает с ИИ какого-то хуя.

2024-01-09 19:19 UTC, LordNest commented
Запрашиваю ревью этой задницы, потому что выправление доступа к атмосу заслуживает отдельного ПРа, которым я буду заниматься после пачки фиксов на оффы

2024-01-09 21:00 UTC, SuhEugene requested changes

2024-01-09 21:00 UTC, SuhEugene commented on mods/ai/code/ai.dm
> +/obj/item/card/id/sierra/ai
Тут точно не сьерра должна быть, а mod или подобное...

2024-01-09 21:00 UTC, SuhEugene commented on mods/ai/code/ai.dm
> +		to_chat(usr, SPAN_WARNING("Color \"[f_color]\" is not allowed!"))
Ахахаха пиздец. Говнокод да и только. Я обязан это переписать

2024-01-09 21:00 UTC, SuhEugene commented on mods/ai/code/ai_hud.dm
> +#define ui_ai_crew_rec "RIGHT-2:30, TOP:0"
Всем дефайнам которые здесь с маленькой буквы нужны андейфайны

2024-01-09 21:00 UTC, SuhEugene commented on mods/legalese_language/code/legalese.dm
> -#define LANGUAGE_LEGALESE       "Legalese"
Это перемещение надо в README этого мода запечатлеть. В разделе про дефайны.

2024-01-09 21:00 UTC, SuhEugene commented on mods/ai/code/ai_screen_objects.dm
> +			if(!input_arg)
Инпут арг может быть 0, а не null так что

```suggestion
			if(isnull(input_arg))
```

2024-01-09 21:00 UTC, SuhEugene commented on mods/ai/code/ai_screen_objects.dm
> +			input_arg= call(input_proc)()
```suggestion
			input_arg = call(input_proc)()
```

2024-01-09 21:00 UTC, SuhEugene commented on mods/ai/code/ai_screen_objects.dm
> +	underlays += template_undelay
Надо переименовать это в template_underlay везде видимо, глупая опечатка

2024-01-09 21:00 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +/*  SIERRA-EDIT - ORIGINAL
Просто SIERRA-REMOVE назови эту часть, а ту что ниже - SIERRA-ADD
Куски очень большие чтобы комментить построчно

Да и, к слову, а неужели они не смогут жить вместе?

Финики просто булк вычитают, а на оффах даже упрощение есть для тех кто стоит пару секунд перед тем как стрелять. Почему бы и нет?

2024-01-09 21:00 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +//[/SIERRA-EDIT]
```suggestion
//[SIERRA-ADD]
	var/is_serial = 0 //the entrie variable that defines should the gun have serial
	var/serial // < most important thing, this is the SERIAL itself
	var/s_type //energy or kinetic
	var/s_gun //gun type, e.g. LP - laep
	//see below

var/global/serials = list()
//[/SIERRA-ADD]
```

А ещё через тире после верхнего сьерра-адд - название мода

2024-01-09 21:00 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +// [SIERRA-EDIT] - BALANCE TWEAKS
А такой мод есть вообще?

2024-01-09 21:00 UTC, SuhEugene commented on code/modules/mob/living/silicon/ai/ai.dm
> +	/mob/living/silicon/ai/proc/show_crew_manifest,
```suggestion
	// [SIERRA-ADD] - AI - ,
	/mob/living/silicon/ai/proc/ai_view_images,
	/mob/living/silicon/ai/proc/ai_take_image,
	/mob/living/silicon/ai/proc/change_floor,
	/mob/living/silicon/ai/proc/show_crew_monitor,
	/mob/living/silicon/ai/proc/show_crew_records,
	/mob/living/silicon/ai/proc/show_crew_manifest,
	// [/SIERRA-ADD] ,
```

2024-01-09 21:00 UTC, SuhEugene commented on code/modules/mob/living/silicon/ai/ai.dm
> +*/
```suggestion
```

2024-01-09 21:00 UTC, SuhEugene commented on code/modules/mob/observer/freelook/chunk.dm
> +		// [/SIERRA-EDIT]
```suggestion
		// [SIERRA-ADD] - AI
		obfuscation.plane = EFFECTS_ABOVE_LIGHTING_PLANE
		// [/SIERRA-ADD]
```

2024-01-09 21:00 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +//[/SIERRA-EDIT]
А точно ли это всё нужно? Оно же сейчас нигде не используется...

2024-01-11 03:45 UTC, SuhEugene requested changes

2024-01-11 03:45 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +/*  SIERRA-REMOVE - ORIGINAL
```suggestion
	// [SIERRA-REMOVE]
	/*
```

2024-01-11 03:45 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +*/
```suggestion
	*/
	// [/SIERRA-REMOVE]
```

2024-01-11 03:45 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +// [SIERRA-ADD]
```suggestion
	// [SIERRA-ADD]
```

2024-01-11 03:45 UTC, SuhEugene commented on code/modules/projectiles/gun.dm
> +// [/SIERRA-ADD]
```suggestion
	// [/SIERRA-ADD]
```

2024-01-11 03:45 UTC, SuhEugene commented on mods/ai/README.md
> +-
```suggestion
- https://github.com/SierraBay/SierraBay12/pull/1773
```

2024-01-11 03:45 UTC, SuhEugene commented on mods/ai/README.md
> +- `code\modules\mob\observer\freelook\chunk.dm`
Во-первых
```suggestion
- `code/modules/mob/observer/freelook/chunk.dm`
```
А во-вторых тут же не оверрайды и немодульные изменения должны находиться, а именно файлы используемые...
Ну то есть из других модпаков или ассеты, но не dm кор кода. Для dm кор кода место в `### Изменения *кор кода*`

2024-01-11 03:45 UTC, SuhEugene commented on mods/legalese_language/README.md
> +- `code/__defines/~mods/~master_defines.dm`
```suggestion
- Отсутствуют
```

Он же уже записан в разделе `### Дефайны`, почто ему тут быть ещё раз?

2024-01-11 08:23 UTC, SuhEugene approved these changes

2024-01-11 08:23 UTC, merged