IPC Cooling organ
SierraBay/SierraBay12 pull request #1782
Opened 2024-01-07 21:06 UTC by Lexanx

ПР делает что-то умное

close #0

### Чейнджлог
```yml
🆑ВашНикнейм
rscadd: Орган Охлаждения для ИПС
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-01-09 21:31 UTC, SuhEugene requested changes

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +## Мод-пример
Название мода

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +- https://github.com/SierraBay/SierraBay12/pull/#####
Номер ПР

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +Этот мод является органом охлаждения для ИПС и внешним охлаждающим устройством для ИПС
```suggestion
Добавляет орган охлаждения для ИПС и внешнее охлаждающее устройство для ИПС
```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +- `mods\ipc_cooling_unit\code\machine.dm`: `mods\ipc_cooling_unit\code\external_cooling_device.dm`, `mods\ipc_cooling_unit\code\cooling_system.dm`
```md
- `файл.dm`: `изменённый proc или var`, `другой proc/var`
- `файл.dm`: `proc/var`
```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +
```suggestion

- Отсутствуют

```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +
```suggestion

- Отсутствуют

```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/datum/_defines.dm
> +#define BP_COOLING "cooling system"
Перемести к моду своему в `code/__defines/~mods`

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	var/interact = 1	//K
K?

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	var/closed = 1
Я предполагаю, что тут должны быть були

```suggestion
	var/active = FALSE
	var/closed = TRUE
```

И абсолютно так же для них должны быть були и в остальном коде ниже

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	cell = new/obj/item/cell/high(src)
У тебя путь к `cell` прописан в самой же этой переменной выше
Его и используем, чтоб удобно было
```suggestion
	if (ispath(cell)
		cell = new cell(src)
```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +				usr.visible_message("<span class='notice'>\The usr] removes \the [cell] from \the [src].</span>", "<span class='notice'>You remove \the [cell] from \the [src].</span>")
Используй дефайн `SPAN_NOTICE("Текст")`

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +					usr.visible_message("<span class='notice'>[usr] inserts \the [C] into \the [src].</span>", "<span class='notice'>You insert \the [C] into \the [src].</span>")
`SPAN_NOTICE`

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +						return
```suggestion
						return TOPIC_NOACTION
```

Я не уверен что это делается именно так, но если меня моя память не подводит, то я написал этот дефайн правильно

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		to_chat(user, "You screwdrived ECD panel")
Бляп, плохо


```suggestion
		to_chat(user, "You [closed ? "tighten" : "unscrew"] ECD panel")
```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +			to_chat(user, "You attach \the [W] to \the [src].")
SPAN_NOTICE

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +				to_chat(user, "There is already a cell loaded!")
Бля там была умная штука с FEEDBACK названием, но я не уверен что она тут применима. Над глянуть.

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +/obj/machinery/external_cooling_device/use_tool(obj/item/W as obj, mob/user as mob)
`return` в этом `use_tool` использован максимально неправильно

Стоит найти другие юз_тул в коде и сделать на их примере, наверное

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	cell = null
Два в одном:
```suggestion
	QDEL_NULL(cell)
```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	set name = "Detach IV Drip"
Я всё понимаю, но мы точно про IV Drip'ы здесь говорим?

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	visible_message("The tube is ripped out of [src.attached]")
```suggestion
	visible_message("\The tube is ripped out of \the [src.attached]")
```

А точно трубка ("tube")?

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/machine.dm
> +		)
Это явно должно быть либо в New, либо в Initialize строчкой:
```dm
LAZYINITLIST(products)
products[BP_COOLING] = list(...)
. = ..()
```

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/machine.dm
> +		)
Аналогично с тем что ниже

2024-01-09 21:31 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/machine.dm
> +				owner.species.passive_temp_gain = 30
Возможно это число 30 стоит вынести в отдельную конфигурируемую переменную. Что скажешь?

2024-01-21 12:08 UTC, Lexanx commented on mods/ipc_cooling_unit/code/machine.dm
> +		)
А зачем это, и почему так как сейчас, плохо?

2024-01-23 12:05 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +				to_chat(user, "There is already a cell loaded!")
```suggestion
				USE_FEEDBACK_FAILURE("There is already a cell loaded!")
```

Все эти штуки в `code/__defines/feedback.dm`
Просто упрощение для того чтобы выводить сообщения неудач

`USE_FEEDBACK_FAILURE("Сообщение")` - в `use_tool`
`FEEDBACK_FAILURE(user, "Сообщение")` - в любых других местах

2024-01-23 12:05 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		to_chat(user, "You [closed ? "tighten" : "unscrew"] ECD panel")
```suggestion
		to_chat(user, SPAN_NOTICE("You [closed ? "tighten" : "unscrew"] ECD panel"))
```

2024-01-23 12:05 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +			to_chat(user, "You attach \the [W] to \the [src].")
```suggestion
			to_chat(user, SPAN_NOTICE("You attach \the [W] to \the [src]."))
```

2024-01-23 12:06 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		to_chat(usr, SPAN_NOTICE("You're in no condition to do that!"))
```suggestion
		to_chat(usr, SPAN_WARNING("You're in no condition to do that!"))
```

2024-01-23 12:07 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		visible_message("\The [attached] is taken off \the [src].")
```suggestion
		visible_message(SPAN_NOTICE("\The [attached] is taken off \the [src]."))
```

2024-01-23 12:07 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	visible_message("\The tube is ripped out of \the [src.attached]")
А точно трубка?

```suggestion
	visible_message(SPAN_WARNING("\The tube is ripped out of \the [src.attached]!"))
```

2024-01-23 12:08 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	to_chat(user, "<span class='notice'>You start to hook up \the [target] to \the [ECD].</span>")
```suggestion
	to_chat(user, SPAN_NOTICE("You start to hook up \the [target] to \the [ECD]."))
```

2024-01-23 12:10 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		user.visible_message("\The [user] fails while trying to hook \the [target] up to \the [ECD], stabbing them instead!")
```suggestion
		user.visible_message(
			SPAN_WARNING("\The [user] fails while trying to hook \the [target] up to \the [ECD], stabbing them instead!"),
			SPAN_WARNING("You fail while trying to hook \the [target] up to \the [ECD], stabbing yourself instead!")
		)
```

2024-01-23 12:10 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	user.visible_message("\The [user] hooks \the [target] up to \the [ECD].")
```suggestion
	user.visible_message(
		SPAN_NOTICE("\The [user] hooks \the [target] up to \the [ECD]."),
		SPAN_NOTICE("You hook \the [target] up to \the [ECD]")
	)
```

2024-01-23 12:11 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/machine.dm
> +		)
```suggestion
/datum/species/machine
	passive_temp_gain = 0  // This should cause IPCs to stabilize at ~80 C in a 20 C environment.(5)

/datum/species/machine/New()
	LAZYINITLIST(has_organ)
	has_organ[BP_COOLING] = /obj/item/organ/internal/cooling_system
	..()
```

2024-01-23 12:13 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/machine.dm
> +		)
https://discord.com/channels/617003227182792704/923696264523173958/1199321319406317590

2024-01-23 12:14 UTC, SuhEugene commented on code/__defines/mobs.dm
> +#define BP_COOLING "cooling system" // IPC Cooling organ
В `code/__defines/~mods/~master_defines.dm` это, и не забыть в `README.md` указать

2024-01-25 14:07 UTC, Lexanx commented on mods/ipc_cooling_unit/code/machine.dm
> +		)
Пятерка тут как напоминание о том, что по дефолту без органа раньше стояло 5

2024-01-25 16:18 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +-->
Ты сделал тут что-то нелегальное. А куда заголовок делся?
Аля
```md
### Изменения *кор кода*
```

Тут же он был

А ещё не `Отсутствуют`, а `- Отсутствуют`, чтобы это как начало списка было

2024-01-25 16:18 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +
Вновь что-то нелегальное. Куда заголовок пропал?

2024-01-25 16:18 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +
```suggestion
```

2024-02-10 01:26 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		usr.unset_machine()
Ну это то ж явно лишнее
```suggestion
```

2024-02-10 01:34 UTC, Lexanx commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		usr.unset_machine()
Откуда я подглядывал. А это spaceheater, там оно стоит аналогично

2024-02-10 01:56 UTC, SuhEugene requested changes, later dismissed
1. Избавляемся от неиспользуемой переменной `interact`
2. Небольшой фикс имени переменной
3. Мелкая красота в виде убирания лишнего энтера
4. Фикс странного афтераттака
5. Лишние ретёрны

Больше я ничего заметить не смог. Просто протыкай приняие предложений и всё *должно быть* замечательно

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/README.md
> +- `mods\ipc_cooling_unit\code\machine.dm`: `owner.species.passive_temp_gain`
```suggestion
- `mods/ipc_cooling_unit/code/machine.dm`:
  - `/datum/species/machine/passive_temp_gain`
  - `/datum/species/machine/New()`
  - `/obj/machinery/organ_printer/robot/New()`
  - `/mob/living/carbon/human/Stat()`
  - `/obj/item/organ/internal/cell/Process()`

```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/machine.dm
> +
Заодно с тем что выше
```suggestion
```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/machine.dm
> +			owner.species.passive_temp_gain = Cooling.get_tempgain()
```suggestion
		var/obj/item/organ/internal/cooling_system/cooling_organ = owner.internal_organs_by_name[BP_COOLING]
		var/normal_passive_temp_gain = 30
		if(!cooling_organ)
			if(owner.bodytemperature > 950 CELSIUS)
				owner.species.passive_temp_gain = 0
			else
				owner.species.passive_temp_gain = normal_passive_temp_gain
		else
			owner.species.passive_temp_gain = cooling_organ.get_tempgain()
```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	var/interact = 1
Это какое-то чудо, которое нигде не присваивается, кроме как тут
```suggestion
```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		return TRUE
```suggestion
	interact(user)
	return TRUE
```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +		popup.open()
```suggestion
	var/list/dat = list()
	dat += "Power cell: "
	if(cell)
		dat += "<A href='byond://?src=\ref[src];op=cellremove'>Installed</A><BR>"
	else
		dat += "<A href='byond://?src=\ref[src];op=cellinstall'>Removed</A><BR>"

	if(!active)
		dat += "<A href='byond://?src=\ref[src];op=Power_Off'>Power On</A><BR>"
	else
		dat += "<A href='byond://?src=\ref[src];op=Power_On'>Power Off</A><BR>"

	dat += "Power Level: [cell ? round(cell.percent(),1) : 0]%<BR><BR>"

	dat += "Set Temperature: "

	dat += "<A href='?src=\ref[src];op=temp;val=-5'>-</A>"

	dat += " [set_temperature]K ([set_temperature-T0C]&deg;C)"
	dat += "<A href='?src=\ref[src];op=temp;val=5'>+</A><BR>"

	var/datum/browser/popup = new(usr, "spaceheater", "External Cooling Device Control Panel")
	popup.set_content(jointext(dat, null))
	popup.set_title_image(usr.browse_rsc_icon(src.icon, "sheater-standby"))
	popup.open()
```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/external_cooling_device.dm
> +	return
```suggestion
```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/cooling_system.dm
> +	return
Ретёрн ничего не возвращающий не нужен в конце функции
```suggestion
```

2024-02-10 01:56 UTC, SuhEugene commented on mods/ipc_cooling_unit/code/cooling_system.dm
> +	return
Я надеюсь тут в буквах не ошибся пока переписывал. В дискорде расписал как что тут и куда. Постарался понятно это сделать.

```suggestion
/obj/item/organ/internal/cooling_system/afterattack(atom/target, mob/user, flag)
	var/obj/item/reagent_containers/glass/beaker = target
	if (!flag || !istype(beaker))
		return ..()

	var/amount = reagents.get_free_space()
	if (safety)
		if (amount <= 0)
			to_chat(user, SPAN_NOTICE("\The [src] is full."))
			return
		if (beaker.reagents.total_volume <= 0)
			to_chat(user, SPAN_NOTICE("\The [dispenser] is empty."))
			return
		amount = beaker.reagents.trans_to_obj(src, refrigerant_max)
		to_chat(user, SPAN_NOTICE("You fill \the [src] with [amount] units from \the [dispenser]."))
		playsound(src.loc, 'sound/effects/pour.ogg', 25, 1)
	else
		amount = src.reagents.trans_to_obj(beaker, refrigerant_max)
		to_chat(user, SPAN_NOTICE("You fill \the [dispenser] with [amount] units from \the [src]."))
		playsound(src.loc, 'sound/effects/pour.ogg', 25, 1)
```

2024-02-27 14:03 UTC, LordNest approved these changes

2024-02-27 14:04 UTC, merged