TWEAK: Merc kits and some fixes
SierraBay/SierraBay12 pull request #1798
Opened 2024-01-13 17:51 UTC by LordNest

ПР делает что-то умное

close #1550

### Чейнджлог
```yml
🆑LordNest
bugfix: Пофиксил баг
wip: Добавил что-то, что ещё в процессе
tweak: Подправил что-то
soundadd: Добавил новый звук
sounddel: Удалил старый звук
rscadd: Вернул из небытия наборы наёмников
rscdel: Удалил из игры что-то старое
imageadd: Добавил новые иконки и картинки
imagedel: Удалил старые иконки и картинки
maptweak: Отредактировал карту
spellcheck: Исправил опечатку
experiment: Добавил что-то экспериментальное
balance: Заребалансил что-то
admin: Сделал что-то с админскими тулзами
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-01-14 15:02 UTC, SuhEugene requested changes
Мод на Respawn as Character бракую полностью. Уже было это добавлено Каддлом в мод `CLIENT_VERBS`, прок называется `/client/proc/respawn_as_human` - `Respawn as Human`. Он просто не был добавлен в список админ-вёрбов.

Остальное там по мелочи.

2024-01-14 15:02 UTC, SuhEugene commented on code/modules/admin/admin_verbs.dm
> +	// [/SIERRA-ADD]
Воооот бы это на ооооффы на саамом деееле. Мечты-мечты...

```suggestion
	// [SIERRA-ADD] - ADMIN_VERBS
	/client/proc/respawn_as_self,
	// [/SIERRA-ADD]
```

2024-01-14 15:02 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/inventory.dm
> +			// [SIERRA-ADD]
Прилепим к моду ССИнпута по причине ну это же для того чтобы на `E` работало круто. И туда же в README.md надо это дописать.
```suggestion
			// [SIERRA-ADD] - SSINPUT
```

2024-01-14 15:02 UTC, SuhEugene commented on maps/sierra/items/modular_computer.dm
> +	verbs |= /obj/item/modular_computer/laptop/verb/rotatelaptop
Оффы не хотят, да?

2024-01-14 15:02 UTC, SuhEugene commented on mods/admin_verbs/README.md
> +- https://github.com/SierraBay/SierraBay12/pull/#####
```suggestion
- https://github.com/SierraBay/SierraBay12/pull/1798
```

2024-01-14 15:02 UTC, SuhEugene commented on mods/admin_verbs/README.md
> +- `mods/_master_files/code/my_modular_override.dm`: `proc/overriden_proc`, `var/overriden_var`
```suggestion
- Отсутствуют
```

2024-01-14 15:02 UTC, SuhEugene commented on mods/admin_verbs/README.md
> +- `code/__defines/~mods/example.dm`: `EXAMPLE_SPEED_MULTIPLIER`, `EXAMPLE_SPEED_BASE`
```suggestion
- Отсутствуют
```

2024-01-14 15:02 UTC, SuhEugene commented on mods/admin_verbs/README.md
> +- `mods/_master_files/icons/obj/alien.dmi`
```suggestion
- Отсутствуют
```

2024-01-14 15:02 UTC, SuhEugene commented on mods/admin_verbs/_admin_verbs.dm
Мод бракую полностью.

2024-01-14 15:02 UTC, SuhEugene commented on mods/fancy_sofas/_fancy_sofas.dme
> +// END_INCLUDE
```suggestion
```

2024-01-14 15:02 UTC, SuhEugene commented on code/modules/admin/admin_verbs.dm
> +	// [/SIERRA-ADD]
А ещё это в моде `CLIENT_VERBS` находится уже
Называется `/client/proc/respawn_as_human` - `Respawn as Human`

```suggestion
	// [SIERRA-ADD] - CLIENT_VERBS
	/client/proc/respawn_as_human,
	// [/SIERRA-ADD]
```

2024-01-14 15:05 UTC, SuhEugene commented on maps/sierra/structures/other.dm
> +		overlays += bmark // add the decal
```suggestion
		AddOverlays(bmark) // add the decal
```

2024-01-14 15:05 UTC, SuhEugene commented on maps/sierra/structures/other.dm
> +			overlays.Cut()
```suggestion
			ClearOverlays()
```

2024-01-14 18:33 UTC, LordNest commented on maps/sierra/items/modular_computer.dm
> +	verbs |= /obj/item/modular_computer/laptop/verb/rotatelaptop
> Оффы не хотят, да?

Ну я давно уже спрашивал, они говорили, что иконки не те. Мб потом как-нибудь

2024-01-15 10:19 UTC, SuhEugene requested changes

2024-01-15 10:19 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/inventory.dm
> +			// [SIERRA-ADD] - SSINPUT
В README.md мода SSINPUT надо обозначить в графе кор кода это изменение

2024-01-15 10:19 UTC, SuhEugene commented on maps/sierra/structures/other.dm
> +			return
Это пиздец.
Юз тул не так работает.

```suggestion
	if(isWelder(W))
		var/obj/item/weldingtool/WT = W
		if(WT.remove_fuel(0, user))
			ClearOverlays()
			bulletholes.Cut()
			hp = initial(hp)
			to_chat(usr, "<span class='notice'>You slice off [src]'s uneven chunks of aluminium and scorch marks.</span>")
		return TRUE
	return ..()
```

2024-01-15 10:19 UTC, SuhEugene commented on maps/sierra/structures/other.dm
> +	var/decaltype = 1 // 1 - scorch, 2 - bullet
Это я щас сам перепишу

2024-01-15 10:19 UTC, SuhEugene commented on maps/sierra/structures/other.dm
> +	if(!Target) return
Ёбаный рот, кто с заглавной переменные называет... Финики бля...

2024-01-15 17:03 UTC, SuhEugene approved these changes

2024-01-15 17:05 UTC, merged