ADD: Sealgen and other macguffins
SierraBay/SierraBay12 pull request #1847
Opened 2024-01-29 16:50 UTC by LordNest

ПР делает что-то умное

close #1381

### Чейнджлог
```yml
🆑ВашНикнейм
bugfix: Пофиксил баг
wip: Добавил что-то, что ещё в процессе
tweak: Подправил что-то
soundadd: Добавил новый звук
sounddel: Удалил старый звук
rscadd: Добавил силген. Занерфил его насколько смог. 
rscdel: Удалил из игры что-то старое
imageadd: Добавил новые иконки и картинки
imagedel: Удалил старые иконки и картинки
maptweak: Отредактировал карту
spellcheck: Исправил опечатку
experiment: Добавил что-то экспериментальное
balance: Заребалансил что-то
admin: Сделал что-то с админскими тулзами
/🆑
```

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2024-01-30 14:19 UTC, ImJustKisik commented
Удаляй этот пр при мне.

2024-01-31 20:18 UTC, SuhEugene requested changes
My conclusion is this code is a war crime.

2024-02-02 19:03 UTC, SuhEugene requested changes
UwU

2024-02-02 19:03 UTC, SuhEugene commented on code/__defines/~mods/~master_defines.dm
> +#define METER_CHECKING "Checking"
Эти двое в глобальных дефайнах не нужны так как используются в одном файле


---

## Руководство "КУДА СУНУТЬ ДЕФАЙН?!?!"

1. Этот дефайн используется только в этом файле?
  - Да: `#define` в начале, `#undef` в конце
  - Нет: Вопрос 2
2. Этот дефайн используется только в этом моде?
  - Да:
    - `#define` в файле `code/_defines.dm`, `#undef` в файле `code/_undefines.dm` или _undefs или как-нибудь очевидно назвать. 
    - `#include "code/_defines.dm"` в начале, затем все остальные файлы, `#include "code/_undefines.dm"` в конце
  - Нет: Пункт 3
3. Этот дефайн используется глобально
  - Суй в `_master_defines`

2024-02-02 19:03 UTC, SuhEugene commented on code/modules/mining/abandonedcrates.dm
> +	// [/SIERRA-EDIT] - UTILITY_ITEMS
```suggestion
	// [SIERRA-EDIT] - UTILITY_ITEMS - Multimeter Avoiding redeclare of var "codelen"
	// var/codelen = 4 // SIERRA-EDIT - ORIGINAL
	codelen = 4
	// [/SIERRA-EDIT] - UTILITY_ITEMS
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/machinery/code/sealing_generator.dm
> +	icon = 'maps/sierra/icons/obj/shielding.dmi'
ЪУЪ

2024-02-02 19:03 UTC, SuhEugene commented on mods/machinery/_machinery.dme
> +#include "code/main.dm"
```suggestion
#include "code/gravity_generator/base.dm"
#include "code/gravity_generator/main.dm"
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/machinery/code/sealing_generator.dm
> +	atmos_canpass = CANPASS_PROC //That's it. //FUCK YOU ZAS
```suggestion
	atmos_canpass = CANPASS_PROC
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/machinery/code/sealing_generator.dm
> +#define SEALGEN_WIRE_POWER		4
```suggestion
#define SEALGEN_WIRE_LOCK  1
#define SEALGEN_WIRE_DENSITY  2
#define SEALGEN_WIRE_POWER  4
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/machinery/code/sealing_generator.dm
> +	icon = 'maps/sierra/icons/obj/shielding.dmi'
ЪУЪ

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/README.md
> +- `code/modules/mob/living.dm`: `proc/overriden_proc`, `var/overriden_var`
Изменения кор кода есть, но не указаны

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/README.md
> +- `"Отсутствуют"`
Don't overthink it
```suggestion
- Отсутствуют
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/README.md
> +- `mods/ntnet/code/NTNet_code.dmi`
Это в каком таком месте...
Вроде не испольщуется он в этом моде

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/README.md
> +- `code/__defines/~mods/utility_items.dm`: `METER_MESURING` `METER_CHECKING` `isMultimeter(A)`
Не забудь удалить отсюда `METER_MESURING` `METER_CHECKING` после того как переместишь их, если их переместишь

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +							to_chat(L, "<span class='notice'>Подаем напряжение...</span>")
```suggestion
							to_chat(L, SPAN_NOTICE("Подаем напряжение..."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +							to_chat(L, "<span class='notice'>Вы не знаете с каким напряжением работает этот провод.</span>")
```suggestion
							to_chat(L, SPAN_NOTICE("Провод пропульсован."))
						else
							to_chat(L, SPAN_WARNING("Вы не знаете с каким напряжением работает этот провод."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +							to_chat(L, "<span class='notice'>Вы не умеете подключать мультиметр.</span>")
```suggestion
							to_chat(L, SPAN_WARNING("Вы не умеете подключать мультиметр."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +							to_chat(L, "<span class='notice'>Перебираем провода...</span>")
```suggestion
							to_chat(L, SPAN_NOTICE("Перебираем провода..."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +							to_chat(L, "<span class='notice'>Переключите мультиметр в режим прозвонки.</span>")
```suggestion
							to_chat(L, SPAN_WARNING("Переключите мультиметр в режим прозвонки."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +						to_chat(L, "<span class='notice'>Вы не знаете как с этим работать.</span>")
```suggestion
						to_chat(L, SPAN_WARNING("Вы не знаете как с этим работать."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
Я не буду заставлять переписывать тебя этот пиздец на early-return'ы, но это просто занавес

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +				to_chat(user, "<span class='notice'>Переключите мультиметр.</span>")
```suggestion
				to_chat(user, SPAN_NOTICE("Мультиметр не реагирует на подключение."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +					to_chat(user, "<span class='notice'>Вы не умеете работать с этим замком.</span>")
```suggestion
					to_chat(user, SPAN_WARNING("Вы не умеете работать с этим замком."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +					to_chat(usr, "<span class='notice'>Ключ не подходит.</span>")
span notice

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +					to_chat(usr, "<span class='notice'>Ключ подходит.</span>")
span notice

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +			to_chat(usr, "<span class='notice'>Переключите мультиметр.</span>")
```suggestion
			to_chat(user, SPAN_NOTICE("Мультиметр не реагирует на подключение."))
```

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +		to_chat(usr, "<span class='notice'>Проверяем замок...</span>")
span notice

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/code/multimeter.dm
> +		visible_message("<span class='warning'>[user] has [locked ? "locked" : "hacked"] [src]!</span>")
span warning

2024-02-02 19:03 UTC, SuhEugene commented on mods/utility_items/README.md
> +Разнообразные полезные инструменты
```suggestion
Модпак добавляет различные предметы, которые будут полезны в использовании, но слишком комплексные, чтобы держать их в файлах карты или где-то ещё.
```

2024-02-03 18:40 UTC, LordNest commented on mods/utility_items/README.md
> +- `mods/ntnet/code/NTNet_code.dmi`
Используется оно. там NTNet_id юзается

2024-02-03 22:29 UTC, SuhEugene commented on mods/utility_items/README.md
> +- `mods/ntnet/code/NTNet_code.dmi`
Тут dmi указан... Надо значит это исправить...

2024-02-03 22:29 UTC, SuhEugene commented on mods/utility_items/README.md
> +- `code/modules/mob/living.dm`: `proc/overriden_proc`, `var/overriden_var`
Всё ещё актуально

2024-02-03 22:30 UTC, SuhEugene requested changes
Два вопроса всё ещё требуют внимания

2024-02-05 11:35 UTC, SuhEugene commented on mods/utility_items/README.md
> +- `code/modules/mining/abandonedcrates.dm` `/obj/structure/closet/crate/secure/loot`
```suggestion
- `code/modules/mining/abandonedcrates.dm` `/obj/structure/closet/crate/secure/loot/var/codelen`
```

2024-02-05 11:36 UTC, SuhEugene approved these changes

2024-02-05 15:30 UTC, SuhEugene submitted a review, later dismissed
ГА согласна с маппером, что смехуёчек в виде окна между спальнями РД и СМО нужно оставить. Следовательно удаление только через воут, увы

2024-02-05 16:11 UTC, merged