CuddleAndFixes
SierraBay/SierraBay12 pull request #188
Opened 2023-03-22 18:12 UTC by cuddleandtea

**Подробное описание** 
Закрытия Ишью не описываю подробно.  В названиях и описаниях коммитов расписаны все изменения. 

**Ишью:**

close #173
close #174
close #165 
close #180 

<details>
<summary>Чейнджлог</summary>

```yml

- bugfix: Music Writer & airlock_controllers_dummy now anchored
- tweak: pile_ripper and crusher icon path fix
- maptweak: У бармена теперь правильный ящик с патронами
- maptweak: Убрал зоны в ксенобио у 4 зон, которые не запитывались, включил зоны в исключения проверки в Sierra_unit_testing
- bugfix: теперь у furniture может быть любая иконка, без необходимости менять furniture.dmi или прописывать новый base_icon
- imageadd: stasis pod now have working icon
- maptweak: Added emerg closet in x:130 Y:077 (Quart area)
- maptweak: Deleted 2 /obj in x:066 Y:177 (Fore Hall area)
- maptweak: Added sofas in library
- maptweak: 3 led lights added in bar
- maptweak: Moved up air alarm in bar dorm room
- maptweak: Missing sofas and chairs in bar
- maptweak: Removed ONLY xenobio areas cell_1, 2, 3
- maptweak: Fixed pew up and down in sauna
- maptweak: Moved up crate with muzzle in med storage
```

</details>

- [х] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [х] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [х] Я запускал сервер со своими изменениями локально и все протестировал.

2023-03-22 20:16 UTC, SuhEugene requested changes
Нашёл там вопросительных моментов...
Правки не стоит принимать все подряд - я могу и ошибаться.
<hr/>
<i>Если задан вопрос - это не значит что что-то неправильно. Это значит, что хочу знать твоё мнение и зачем сделано. Ну это так, к слову.</i>

2023-03-22 20:16 UTC, SuhEugene commented on code/game/machinery/embedded_controller/airlock_controllers_dummy.dm
> +	anchored = 1
В sierra-tweaks это дело лучше перенести.
```dm
/obj/machinery/dummy_airlock_controller
	icon_state = "airlock_control_off"
	anchored = TRUE
```
Также стоит заметить, что `anchored = TRUE`. Используем `TRUE`/`FALSE`, а не `1`/`0` в логических переменных

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	},
Там не нужны эти led'ы, ибо они не смешаются на стену и это выглядит криво очень. Вот эти три:
![image](https://user-images.githubusercontent.com/32931701/227024681-f02cfc13-83fe-4ae5-9007-679bda815938.png)

```suggestion
```

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	},
См. ревью выше
```suggestion
```

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	},
См. ревью выше (х2)
```suggestion
```

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	pixel_x = -3;
Ему точно нужно `pixel_x` задавать через маппинг?

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	pixel_x = -3;
Аналогично вопросу выше

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	anchored = 1
`anchored = 1` был прописан в коде, здесь не нужен
```suggestion
	pixel_x = -28
```

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	icon_state = "middle"
Очень странным нахожу то, что `icon_state` задан через маппинг. Такое скорее всего должно быть задано в коде.

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	anchored = 1
Аналогично ревью мьюзикрайтера выше
```suggestion
	pixel_y = 28
```

2023-03-22 20:16 UTC, SuhEugene commented on maps/sierra/sierra-2.dmm
> +	anchored = 1
Аналогично ревью музикрайтера выше (х2)
```suggestion
	pixel_x = 28
```

2023-03-22 20:16 UTC, SuhEugene commented on packs/infinity/items/music_player/music_writer.dm
> +	anchored = 1
Булевы переменные - булевы значения. Не числа.
```suggestion
	anchored = TRUE
```

2023-03-22 23:27 UTC, cuddleandtea commented on maps/sierra/sierra-2.dmm
> +	pixel_x = -3;
Да, он так сделан на Сьерре и выглядит получше

2023-03-22 23:28 UTC, cuddleandtea commented on maps/sierra/sierra-2.dmm
> +	icon_state = "middle"
icon state у них по коду стоит у всех стандартный, я лишь отобразил стейты для SDMM. Можно и убрать

2023-03-22 23:29 UTC, cuddleandtea commented on maps/sierra/sierra-2.dmm
> +	pixel_x = -3;
Да, он так сделан на Сьерре и выглядит получше

2023-03-23 10:20 UTC, cuddleandtea commented on maps/sierra/sierra-2.dmm
> +	pixel_x = -3;
Не могу зарезольвить почему-то

2023-03-24 13:24 UTC, SuhEugene requested changes
Я стараюсь не душить, но у меня очень плохо это получается.
Я обязательно создам файл, объясняющий что и как правильно делать... Обязательно создам...

2023-03-24 13:24 UTC, SuhEugene commented on maps/sierra/sierra-1.dmm
> -	},
Клозет удалил, но не добавил на его место новый

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/maps/sierra/structures/closets/services.dm
Это можно (и нужно) менять в `/maps/sierra/structures/closets/services.dm`
`/maps/sierra/**` - не кор код.

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/_pack.dm
> +#include "code\game\machinery\embedded_controller\airlock_controllers_dummy.dm"
Переместить в `objects\machines\machinery.dm`
## Почему?
- `objects\machines` потому что здесь упрощенные пути.
- `machinery.dm` потому что аля сборочный файл **мелких** изменений в машинах, аля добавление `anchored` и ничего более.

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/_pack.dm
> +#include "code\game\objects\structures\crates_lockers\closets\utility_closets.dm"
Переместить в `objects\structures\closets.dm`, потому что тут упрощенные пути.

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/objects/structures/crates_lockers/closets/utility_closets.dm
> +	)
Не вижу здесь отличий от оригинального файла, следовательно оно не нужно
```suggestion
```

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/objects/structures/crates_lockers/closets/utility_closets.dm
> +	)
`WillContain` совпадает с `WillContain` родителя, следовательно не нужен
```suggestion
```

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/objects/structures/crates_lockers/closets/utility_closets.dm
> +	closet_appearance = /singleton/closet_appearance/oxygen
Описание и внешний вид совпадают с описанием и внешним видом родителя, следовательно не нужны
```suggestion
```

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Нужно писать лишь изменения. Копировать оригинальную информацию не нужно - она унаследуется.
По итогу, как я понимаю, этот файл должен выглядеть примерно так:
```dm
/obj/structure/closet/emcloset/anchored
	name = "anchored emergency closet"
	anchored = TRUE
```

Ага, всего три строчки. Да, так просто.

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/code/game/machinery/embedded_controller/airlock_controllers_dummy.dm
Оригинайльный файл выглядит вот так:
```dm
/obj/machinery/dummy_airlock_controller
	name = "airlock control terminal"
	icon = 'icons/obj/airlock_machines.dmi'
	icon_state = "airlock_control_standby"
	layer = ABOVE_OBJ_LAYER
```
Твой вот так:
```dm
/obj/machinery/dummy_airlock_controller
	name = "airlock control terminal"
	icon = 'icons/obj/airlock_machines.dmi'
	icon_state = "airlock_control_off"
	layer = ABOVE_OBJ_LAYER
	anchored = TRUE
```

Отличия? Только `anchored = TRUE`.
Следовательно только его и нужно писать. Остальное унаследуется из оригинального файла.

Достаточно написать:
```dm
/obj/machinery/dummy_airlock_controller
	anchored = TRUE
```
и всё будет работать.

2023-03-24 13:24 UTC, SuhEugene commented on packs/sierra-tweaks/_pack.dm
> +
Для этого `sierra-tweaks` не нужен, ибо карта сьерры - не кор код. На оффах нет сьерры.
Это менять можно прямо в `maps\sierra\structures\closets\services.dm`

2023-03-26 06:37 UTC, LordNest approved these changes

2023-03-26 10:08 UTC, cuddleandtea commented on packs/sierra-tweaks/maps/sierra/structures/closets/services.dm
Бляяяяяяха

2023-03-26 10:15 UTC, cuddleandtea commented on maps/sierra/sierra-1.dmm
> -	},
[Удалил ящик, застрявший в шлюзе при маппинге](https://github.com/SierraBay/SierraBay12/pull/188/commits/544c5728ed9061d60f262c1ca9b83b89d64c6c13) Это ошибка маппера. Я его случайно под шлюзом заметил

2023-03-26 10:20 UTC, cuddleandtea commented on packs/sierra-tweaks/code/game/machinery/embedded_controller/airlock_controllers_dummy.dm
Принял, понял

2023-03-26 10:24 UTC, cuddleandtea commented on packs/sierra-tweaks/_pack.dm
> +
Ух ля...

2023-03-26 10:35 UTC, cuddleandtea commented on packs/sierra-tweaks/_pack.dm
> +#include "code\game\machinery\embedded_controller\airlock_controllers_dummy.dm"
Я не понял почему возможно в принципе сливание отдельного файла airlock_controllers_dummy.dm с machinery.dm И как игра поймет, что я сделал изменения именно в первом файле. Это же очень запутывает. Тот же код. Разве систему чёткого пути и ветвления не лучше оставить, чем прописывать всё в одном файле?

2023-03-26 11:05 UTC, SuhEugene approved these changes
Замечтально ![image](https://user-images.githubusercontent.com/32931701/227771553-dd46fb58-e11a-474a-8444-594da3dd0d45.png)

2023-03-26 11:15 UTC, merged