Fix Sierra map issues
SierraBay/SierraBay12 pull request #1893
Opened 2024-02-12 17:20 UTC by YegorKandziuba

Много изменений

close #1884
close #1878
close #1876
close #1874
close #1873
close #1870

### Скриншоты
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/2044f7b9-ee56-406b-80c8-b3470d2e92d5)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/cf17d4dd-e65c-4cfd-99f6-ad5a938b891d)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/cf7eb8d7-e638-4da6-bd96-53ceab60099c)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/1f75932a-587c-4d9b-9370-129221d23d75)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/0f4307ec-5763-4523-8084-85f4885e6594)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/31287c35-a76b-4300-a337-b75685ebfb43)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/cbef3cb3-7bd6-4da6-bb8a-a35e86a5cdab)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/dcdfd20e-8671-4f84-b73a-57bf903e32f6)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/28fb25f0-933c-4809-9506-1a92114a6c96)
![image](https://github.com/SierraBay/SierraBay12/assets/83637364/92720575-ad42-4efe-a75d-001a5cb88d34)

### Чейнджлог
```yml
🆑KandJX
maptweak: Переработка дорм
maptweak: Переработка сауны
maptweak: Решение ишуев по карте
tweak: СЕ выдан раундстартом пояс с Хайтир инструментами
tweak: Утилити пояс теперь вмещает в себя РЦД и ПейнтСпреер.
maptweak: Добавлена карта авейдереликта "Пиратской Шахты"
tweak: Порт пропов для сауны от ДаркСовета с проекта ФайнлДестинейшн
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-02-12 23:30 UTC, SuhEugene commented on maps/sierra/items/items.dm
> +		)
Блин вот бы новый код писать красиво
```suggestion
	)
```

2024-02-12 23:31 UTC, SuhEugene commented on mods/_maps/miningpirate/_map_miningpirate.dme
> +
Это явно лишнее
```suggestion
```

2024-02-12 23:33 UTC, SuhEugene requested changes

2024-02-12 23:33 UTC, SuhEugene commented on mods/sauna_props/README.md
Файл совершенно не заполнен.

И... Лучше создавать моды не копипастом, а используя скрипт, так хоть базовая инфа автозаполнится.

2024-02-12 23:34 UTC, SuhEugene commented on mods/_maps/miningpirate/_map_miningpirate.dme
> +#include "code/miningpirate.dm"
```suggestion
#include "code/miningpirate.dm"
```

2024-02-12 23:35 UTC, SuhEugene commented on mods/sauna_props/_sauna_props.dme
> +#include "code/sauna_props.dm"
```suggestion
#include "code/sauna_props.dm"
```

2024-02-12 23:36 UTC, SuhEugene requested changes

2024-02-12 23:36 UTC, SuhEugene commented on mods/sauna_props/code/sauna_props.dm
> +		user.visible_message("<span class='warning'>\The [user] begins to clean \the [T].</span>")
```suggestion
		user.visible_message(SPAN_WARNING("\The [user] begins to clean \the [T]."))
```

2024-02-12 23:36 UTC, SuhEugene commented on mods/sauna_props/code/sauna_props.dm
> +			to_chat(user, "<span class='notice'>You have finished mopping!</span>")
```suggestion
			to_chat(user, SPAN_NOTICE("You have finished mopping!"))
```

2024-02-12 23:42 UTC, SuhEugene requested changes
Моду `sauna_props` нужен `README.md` файл

2024-02-12 23:51 UTC, SuhEugene approved these changes

2024-02-13 04:58 UTC, LordNest requested changes
Постеры контрабандные нужно убрать из дорминториев. Оставить только нормальные.

2024-02-13 04:58 UTC, LordNest commented on maps/sierra/z1-z5_sierra.dmm
> +/obj/item/contraband/poster,
Убрать контрабандные постеры из дорминториев

2024-02-13 06:30 UTC, YegorKandziuba commented on maps/sierra/z1-z5_sierra.dmm
> +/obj/item/contraband/poster,
Это не в дормах

2024-02-13 06:30 UTC, YegorKandziuba commented on maps/sierra/z1-z5_sierra.dmm
> +/obj/item/contraband/poster,
Это в техах. И там они были ещё со времен СССР. Я лишь слегка подвинул

2024-02-13 07:35 UTC, LordNest approved these changes

2024-02-13 07:35 UTC, merged