SCGF Patrol Craft
SierraBay/SierraBay12 pull request #194
Opened 2023-03-26 12:02 UTC by LordNest

Данный PR добавляет патрульный корабль ЦПСС со следующими отличиями от оригинала
* Invider заменён на Z9
* LCD заменена на Z8
* Барабанный дробовик заменён на Узи
* Дробовик помповый заменён на боевой

close #52 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
rscadd: Добавлена карта SCGF Patrol Craft
maptweak: Удалил лишний АПЦ на карте патруля и добавил новые эмблемы от Вольфора
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2023-03-27 11:11 UTC, SuhEugene requested changes
Проверил 12 из 16. Дальше лень, потом как-нибудь.

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/_map_sentinel.dme
> +// END_INCLUDE
```suggestion
#ifndef MODPACK_MAP_SENTINEL
#define MODPACK_MAP_SENTINEL

#include "sentinel.dm"

#endif
```

А также я требую подключения всех файлов карты и составления модпака по [гайду из PR#201](https://github.com/SierraBay/SierraBay12/blob/fda88f7edcb4b4fb640d36c7947d04e44ecd30d8/mods/README.md), который пока что не замёржен.

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel.dm
> +		)
Красивше
```suggestion
	initial_generic_waypoints = list(
		"nav_patrol_1",
		"nav_patrol_2",
		"nav_patrol_3",
		"nav_patrol_4",
		"nav_hangar_reaper"
	)
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel.dm
> +		)
ЫАЫЭЫЭАЭЫАЫЫ!!!
```suggestion
	initial_restricted_waypoints = list(
		"Reaper" = list("nav_hangar_reaper")
	)
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel.dm
> +	..()
```suggestion
#define PATROL_SHIP_PREFIX pick("Sentinel","Cavalry","Scarabaeus","Heretic","Apocalypse","Calamatious","Terror","Pandemonium","Anubis","Hound","Stalker","Avatar","Ultimatum","Goliath","Tyrant","Nemesis","Hydra","Stormhawk","Manticore","Basilisk")
/obj/effect/overmap/visitable/ship/patrol/New()
	name = "SFV [PATROL_SHIP_PREFIX], \a [name]"
	for(var/area/ship/patrol/A)
		A.name = "\improper [name] - [A.name]"
		GLOB.using_map.area_purity_test_exempt_areas += A.type
	..()
#undef PATROL_SHIP_PREFIX
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel.dm
> +	spawn_weight = 1 // INF, spawn_weight = 0.5
No infinity
```suggestion
	player_cost = 7
	spawn_weight = 1
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel.dm
> +	//req_access = list(access_security)
```suggestion
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel.dm
> +	archetype = /singleton/submap_archetype//away_scg_patrol
Лишний слеш чи шо?
```suggestion
	archetype = /singleton/submap_archetype/away_scg_patrol
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_areas.dm
> +	req_access = list(access_away_cavalry)
```suggestion
#define PATROL_ENG_AMBIENCE list('sound/ambience/ambigen3.ogg','sound/ambience/ambigen4.ogg','sound/ambience/ambigen5.ogg','sound/ambience/ambigen6.ogg','sound/ambience/ambigen7.ogg','sound/ambience/ambigen8.ogg','sound/ambience/ambigen9.ogg','sound/ambience/ambigen10.ogg','sound/ambience/ambigen11.ogg','sound/ambience/ambieng1.ogg')
/area/ship/patrol/maintenance/atmos
	name = "\improper Atmospherics Comparment"
	icon_state = "atmos"
	ambience = PATROL_ENG_AMBIENCE
	req_access = list(access_away_cavalry)

/area/ship/patrol/maintenance/engine
	icon_state = "engine"
	ambience = PATROL_ENG_AMBIENCE
	req_access = list(access_away_cavalry)
#undef PATROL_ENG_AMBIENCE
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_areas.dm
> +
```suggestion
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_crew.dm
> +					 SKILL_EVA = SKILL_BASIC)
```suggestion
	min_skill = list(
		SKILL_COMBAT  = SKILL_BASIC,
		SKILL_WEAPONS = SKILL_BASIC,
		SKILL_HAULING = SKILL_BASIC,
		SKILL_MEDICAL = SKILL_BASIC,
		SKILL_EVA     = SKILL_BASIC
	)
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_crew.dm
> +					 SKILL_EVA = SKILL_BASIC)
```suggestion
	min_skill = list(
		SKILL_COMBAT  = SKILL_BASIC,
		SKILL_WEAPONS = SKILL_BASIC,
		SKILL_HAULING = SKILL_BASIC,
		SKILL_MEDICAL = SKILL_BASIC,
		SKILL_PILOT   = SKILL_ADEPT,
		SKILL_EVA     = SKILL_BASIC
	)
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_crew.dm
> +					 SKILL_EVA = SKILL_BASIC)
```suggestion
	min_skill = list(
		SKILL_COMBAT    = SKILL_BASIC,
		SKILL_WEAPONS   = SKILL_BASIC,
		SKILL_HAULING   = SKILL_ADEPT,
		SKILL_MEDICAL   = SKILL_EXPERT,
		SKILL_ANATOMY   = SKILL_BASIC,
		SKILL_CHEMISTRY = SKILL_BASIC,
		SKILL_EVA       = SKILL_BASIC
	)
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_crew.dm
> +					 SKILL_DEVICES = SKILL_BASIC)
Бляяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяя

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_crew.dm
> +					 SKILL_DEVICES = SKILL_BASIC)
```suggestion
	min_skill = list(
		SKILL_COMBAT  = SKILL_BASIC,
		SKILL_WEAPONS = SKILL_BASIC,
		SKILL_HAULING = SKILL_ADEPT,
		SKILL_MEDICAL = SKILL_BASIC,
		SKILL_ATMOS   = SKILL_BASIC,
		SKILL_ENGINES = SKILL_ADEPT,
		SKILL_DEVICES = SKILL_BASIC,
		SKILL_EVA     = SKILL_ADEPT,
		SKILL_ELECTRICAL   = SKILL_ADEPT,
		SKILL_CONSTRUCTION = SKILL_ADEPT,
	)
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_items.dm
> + */
```suggestion
```

2023-03-27 11:11 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_shuttle.dm
> +	docking_controller = "nuke_shuttle_dock_airlock" */
Вижу комментарий - советую удалить. keklown.

Или удаляй, или `// SIERRA TODO: сделать чота` писать надо, или ПР всё-же драфт
```suggestion
```

2023-03-28 15:06 UTC, SuhEugene commented on mods/maps/sentinel/sentinel.dm
> +#include "sentinel_turbolift.dm"
В `mods/maps/sentinel/_map_sentinel.dme` давай это дело

2023-03-28 15:06 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_crew.dm
> +/var/const/access_away_cavalry_commander = "ACCESS_CAVALRY_COMMANDER"
```suggestion
var/global/const/access_away_cavalry = "ACCESS_CAVALRY"
var/global/const/access_away_cavalry_fleet_armory = "ACCESS_CAVALRY_EMERG_ARMORY"
var/global/const/access_away_cavalry_ops = "ACCESS_CAVALRY_OPS"
var/global/const/access_away_cavalry_pilot = "ACCESS_CAVALRY_PILOT"
var/global/const/access_away_cavalry_captain = "ACCESS_CAVALRY_CAPTAIN"
var/global/const/access_away_cavalry_commander = "ACCESS_CAVALRY_COMMANDER"
```

2023-03-28 15:06 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_areas.dm
> +	req_access = list(access_away_cavalry)
Ну как это - файл без пустой строки в конце?
```suggestion
	req_access = list(access_away_cavalry)

```

2023-03-28 15:06 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_turbolift.dm
> +		)
```suggestion
	areas_to_use = list(
		/area/turbolift/sentinel_first,
		/area/turbolift/sentinel_second
	)
```

2023-03-29 08:04 UTC, LordNest commented on mods/maps/sentinel/sentinel.dm
> +#include "sentinel_turbolift.dm"
> В `mods/maps/sentinel/_map_sentinel.dme` давай это дело

так все же карты инициализируют сначала базовый dm а потом уже всякие приколы. 
Не сломается ничего от этого?

2023-03-31 20:20 UTC, SuhEugene requested changes
Да мне бля в принципе страшно сюда смотреть. Тут много букав читать.
Да не хочу я это ревьювить

2023-03-31 20:27 UTC, SuhEugene requested changes
Ладно, это ласт ревью (надеюсь) от меня.
Конечно я хрен знает что тут Либерия забыла, если это сентинель.

Поправь мелкие недочёты и можно поносить в прод.


А ещё хочу чтобы пояснил за мем с удалением бранчей с Либерии в дискордике с пингом

2023-03-31 20:27 UTC, SuhEugene commented on maps/away_sites_testing/away_sites_testing.dm
> +//	#include "../../mods/maps/sentinel/_map_sentinel.dme" Ises too many assets from Torch, which makes separate testing obsolete
Оставь здесь такой тег чтобы (мне) потом пофиксить не забыть

```suggestion
// SIERRA TODO: fix that shit
//	#include "../../mods/maps/liberia/_map_liberia.dme" Uses too many assets from mods and Sierra, which makes separate testing obsolete
//	#include "../../mods/maps/sentinel/_map_sentinel.dme" Ises too many assets from Torch, which makes separate testing obsolete
```

2023-03-31 20:27 UTC, SuhEugene commented on mods/maps/liberia/liberia_jobs.dm
> -	)
:achE:

2023-03-31 20:27 UTC, SuhEugene commented on mods/maps/sentinel/sentinel_crew.dm
> +					 SKILL_EVA = SKILL_BASIC)
```suggestion
	min_skill = list(
		SKILL_COMBAT  = SKILL_BASIC,
		SKILL_WEAPONS = SKILL_BASIC,
		SKILL_HAULING = SKILL_BASIC,
		SKILL_MEDICAL = SKILL_BASIC,
		SKILL_PILOT   = SKILL_ADEPT,
		SKILL_EVA     = SKILL_BASIC
	)
```

2023-03-31 20:35 UTC, LordNest commented on mods/maps/liberia/liberia_jobs.dm
> -	)
Оно наследует от родителя, всё в порядке

2023-03-31 20:38 UTC, SuhEugene approved these changes
@ImJustKisik, твой выход

2023-04-02 05:45 UTC, ImJustKisik approved these changes

2023-04-02 17:52 UTC, merged