Фиксики
SierraBay/SierraBay12 pull request #202
Opened 2023-03-27 06:29 UTC by Atufancheg

Решение дефектов первого теста

fix #114 
close #148 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Возвращена проверка таймера для эмоутов
tweak: Перенесен набор иконок HUD с ss220
/🆑
```

</details>

- [ x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-03-27 10:27 UTC, SuhEugene requested changes

2023-03-27 10:27 UTC, SuhEugene commented on icons/mob/screen/midnight-inf.dmi
`icons/mob/screen/midnight-inf.dmi` -> `packs/infinity/icons/mob/screen/midnight-inf.dmi`

2023-03-27 10:27 UTC, SuhEugene commented on packs/sierra-tweaks/_pack.dm
> +#include "modules\emotes\emotes_mob.dm"
Изменить вот так
```suggestion
#include "mob\emotes.dm"
```
И перенести под `// Mob`
Ну что красииииво

2023-03-27 10:27 UTC, SuhEugene commented on packs/sierra-tweaks/modules/emotes/emotes_mob.dm
> +	. = ..() && emoteCooldownCheck() == 1
Любое не нулевое значение - истина (`TRUE`)
```suggestion
	. = ..() && emoteCooldownCheck()
```

2023-03-27 10:27 UTC, SuhEugene commented on packs/sierra-tweaks/objects/machines/alarm.dm
Вот подобную громадную херню лучше не переносить, а прямо в кор коде править,
оставив старый код и добавив новый в таком формате:
```dm
// do something  // BAY
do something new // SIERRA
```

<hr/>

Либо же
```dm
// [BAY]
// do something old 1
// do something old 2
// [/BAY]

// [SIERRA]
do somthing new 1
do something new 2
// [/SIERRA]
```
для случая с неколькими строками

2023-03-27 10:27 UTC, SuhEugene commented on baystation12.dme
> +#include "packs\sierra-tweaks\_pack.dm"
Не наааааааааааадо сюда это вот так вот делать вот дааааааа
```suggestion
```
Паки и моды подключаются в коде карты ([`maps/sierra/sierra.dm`](https://github.com/SierraBay/SierraBay12/blob/dev220/maps/sierra/sierra.dm)), здесь не надо такого

2023-03-27 10:27 UTC, SuhEugene commented on code/modules/client/ui_style.dm
> +	"Midnight"     = 'icons/mob/screen/midnight-inf.dmi',
Изменения в кор коде нужно обозначать
И обозначать с указанием того, что было изменено
```suggestion
	// "Midnight"     = 'icons/mob/screen/midnight.dmi',                 // BAY,
	"Midnight"     = 'packs/infinity/icons/mob/screen/midnight-inf.dmi', // SIERRA,
```
Не спрашивай про запятые в конце комметариев. Это просто нужно. Просто потому что юнит-тесты.

2023-03-27 10:27 UTC, SuhEugene commented on packs/sierra-tweaks/objects/machines/alarm.dm
> +		dat += "<HTML><HEAD></HEAD><BODY><TT><B>[stars("Fire alarm")]</B> [d1]\n<HR>The current security level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime L
В попапе не нужны никакие HTML, BODY, TT. Попап начинается с контента.
```suggestion
		dat += "<B>[stars("Fire alarm")]</B> [d1]\n<HR>The current security level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute ? text("[]:", minute) : null)][second] <A href='?src=\ref[src];tp=-30'>-</A> <A href='?src=\ref[src];tp=-1'>-</A> <A href='?src=\ref[src];tp=1'>+</A> <A href='?src=\ref[src];tp=30'>+</A>"
```

2023-03-27 10:27 UTC, SuhEugene commented on packs/sierra-tweaks/objects/machines/alarm.dm
> +		dat += "<HTML><HEAD></HEAD><BODY><TT><B>Fire alarm</B> [d1]\n<HR>The current alert level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute
Только контент

```suggestion
		dat += "<B>Fire alarm</B> [d1]\n<HR>The current alert level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute ? "[minute]:" : null)][second] <A href='?src=\ref[src];tp=-30'>-</A> <A href='?src=\ref[src];tp=-1'>-</A> <A href='?src=\ref[src];tp=1'>+</A> <A href='?src=\ref[src];tp=30'>+</A>"
```

2023-03-27 11:01 UTC, Atufancheg commented on packs/sierra-tweaks/modules/emotes/emotes_mob.dm
> +	. = ..() && emoteCooldownCheck() == 1
противоречит моим религиозным соображениям. Дзен питона заповеди 1 и 2. Если бы название метода начиналось с check, то может быть

2023-03-27 11:02 UTC, Atufancheg commented on icons/mob/screen/midnight-inf.dmi
учту

2023-03-27 11:02 UTC, Atufancheg commented on packs/sierra-tweaks/_pack.dm
> +#include "modules\emotes\emotes_mob.dm"
учту

2023-03-27 11:08 UTC, Atufancheg commented on code/modules/client/ui_style.dm
> +	"Midnight"     = 'icons/mob/screen/midnight-inf.dmi',
учту

2023-03-27 11:08 UTC, Atufancheg commented on packs/sierra-tweaks/objects/machines/alarm.dm
принял к сведению

2023-03-27 11:36 UTC, SuhEugene requested changes

2023-03-27 11:36 UTC, SuhEugene commented on icons/mob/screen/midnight-inf.dmi
В `code/modules/client/ui_style.dm` файл переименовал, но не перенёс в `packs/infinity/icons/mob/screen/midnight-inf.dmi`

2023-03-27 11:36 UTC, SuhEugene commented on packs/sierra-tweaks/_pack.dm
> +
`// Mob` есть чуть ниже, тебе туда. Плюс учти что там всё в алфавитном порядке.

2023-03-27 11:36 UTC, SuhEugene commented on packs/sierra-tweaks/_pack.dm
> +#include "objects\machines\alarm.dm"
```suggestion
```
Отсюда мы это удаляем, потому что изменения будут перенесены куда? В кор код.

2023-03-27 11:36 UTC, SuhEugene commented on packs/sierra-tweaks/objects/machines/alarm.dm
Тут нужно не только к сведению принять, но и перенести...
Измненения в кор код, да, согласно описанию выше...

2023-03-28 10:21 UTC, SuhEugene requested changes

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +		var/dat += "<HTML><HEAD></HEAD><BODY><TT><B>Fire alarm</B> [d1]\n<HR>The current alert level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(min
Там `+` не было
А также это закомментировать надо
```suggestion
		// var/dat = "<HTML><HEAD></HEAD><BODY><TT><B>Fire alarm</B> [d1]\n<HR>The current alert level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute ? "[minute]:" : null)][second] <A href='?src=\ref[src];tp=-30'>-</A> <A href='?src=\ref[src];tp=-1'>-</A> <A href='?src=\ref[src];tp=1'>+</A> <A href='?src=\ref[src];tp=30'>+</A>\n</TT></BODY></HTML>"
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
>  		show_browser(user, dat, "window=firealarm")
То что было на бее - в комментарий. Оно не должно работать, оно ***было***
```suggestion
		// show_browser(user, dat, "window=firealarm")
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +//		[BAY]
Правильно вот так
```suggestion
		// [BAY]
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +// 		[SIERRA]
```suggestion
		// [/BAY]
		// [SIERRA]
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +// 		[/SIERRA]
```suggestion
		// [/SIERRA]
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
>  		show_browser(user, dat, "window=firealarm")
Прошлое в комментарий
```suggestion
 		// var/dat = "<HTML><HEAD></HEAD><BODY><TT><B>[stars("Fire alarm")]</B> [d1]\n<HR>The current security level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute ? text("[]:", minute) : null)][second] <A href='?src=\ref[src];tp=-30'>-</A> <A href='?src=\ref[src];tp=-1'>-</A> <A href='?src=\ref[src];tp=1'>+</A> <A href='?src=\ref[src];tp=30'>+</A>\n</TT></BODY></HTML>"
 		// show_browser(user, dat, "window=firealarm")
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +//		[BAY]
```suggestion
		// [BAY]
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +// 		[SIERRA]
```suggestion
		// [/BAY]
		// [SIERRA]
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +		popup.set_content(JOINTEXT(dat))
`JOINTEXT` нужен был бы, если бы `dat` был массивом/списком (`list()`)
Но `dat` - обычный текст, строка
```suggestion
		popup.set_content(dat)
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +		popup.set_content(JOINTEXT(dat))
Аналогично тому, что описано выше

```suggestion
		var/dat = "<B>[stars("Fire alarm")]</B> [d1]\n<HR>The current security level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute ? text("[]:", minute) : null)][second] <A href='?src=\ref[src];tp=-30'>-</A> <A href='?src=\ref[src];tp=-1'>-</A> <A href='?src=\ref[src];tp=1'>+</A> <A href='?src=\ref[src];tp=30'>+</A>"
		popup.set_content(dat)
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +// 		[/SIERRA]
```suggestion
		// [/SIERRA]
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +	var/dat // SIERRA
Здесь интерфейс не поделён на части, да и дат ты не инициализировал как список (лист), так что смвсла не имеет
```suggestion
```

2023-03-28 10:21 UTC, SuhEugene commented on code/game/machinery/alarm.dm
> +		var/dat += "<B>Fire alarm</B> [d1]\n<HR>The current alert level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute ? "[minute]:" : null)][se
`var/` пишется **только** при объявлении переменной, так что нужно:
- Либо удалить строчку 1076, а здесь `+=` заменить на `=`
- Либо удалить здесь `var/`, оставив `dat += ...`

И я склоняюсь к первому варианту, ибо `dat` и не дополняется выше по коду.


```suggestion
		var/dat = "<B>Fire alarm</B> [d1]\n<HR>The current alert level is <b>[security_state.current_security_level.name]</b><br><br>\nTimer System: [d2]<BR>\nTime Left: [(minute ? "[minute]:" : null)][second] <A href='?src=\ref[src];tp=-30'>-</A> <A href='?src=\ref[src];tp=-1'>-</A> <A href='?src=\ref[src];tp=1'>+</A> <A href='?src=\ref[src];tp=30'>+</A>"
```

2023-03-28 16:03 UTC, SuhEugene approved these changes
![image](https://user-images.githubusercontent.com/32931701/228299927-09637b64-8177-4661-8280-bba9bf48c2ae.png)

2023-03-28 17:10 UTC, merged