Bugfix: Alarm Monitor
SierraBay/SierraBay12 pull request #204
Opened 2023-03-27 17:49 UTC by ImJustKisik

Починил консоль алярмов
 fixes: #160
<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Инженерами НаноТрейзен исправлена ошибка в программе мониторинга тревог. 
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-03-27 17:58 UTC, SuhEugene requested changes
Если уж и срать, то срать красиво

2023-03-27 17:58 UTC, SuhEugene commented on code/game/machinery/computer/station_alert.dm
> -	alarm_monitor.register_alarm(src, /atom/proc/update_icon)
```dm
	// alarm_monitor = new monitor_type(src) // BAY
	// alarm_monitor.register_alarm(src, /atom/proc/update_icon) // BAY
```

2023-03-27 17:58 UTC, SuhEugene commented on code/game/machinery/computer/station_alert.dm
> +		alarm_monitor.register_alarm(src, /atom/.proc/update_icon)
```suggestion
		alarm_monitor.register_alarm(src, /atom/.proc/update_icon) // SIERRA
```

2023-03-27 17:58 UTC, SuhEugene commented on code/modules/alarm/alarm.dm
> +		last_z_level = origin.get_alarm_z(origin)
Во-первых
```suggestion
		// last_z_level = origin.loc ? origin.loc.z : 0 // BAY
		last_z_level = origin.get_alarm_z(origin) // SIERRA
```

Во-вторых на кой хрен ты передаёшь `origin` как аргумент, если прок аргументов не принимает?

2023-03-27 17:58 UTC, SuhEugene commented on code/modules/alarm/alarm.dm
> +	return contents.len ? get_z(contents[1]) : 0
```suggestion
// [SIERRA]
/atom/proc/get_alarm_z()
	return get_z(src)

/area/get_alarm_z()
	return contents.len ? get_z(contents[1]) : 0
// [/SIERRA]
```

2023-03-29 17:28 UTC, ImJustKisik commented on code/modules/alarm/alarm.dm
> +		last_z_level = origin.get_alarm_z(origin)
Всё как и должно быть

2023-03-29 18:43 UTC, SuhEugene requested changes, later dismissed

2023-03-29 18:43 UTC, SuhEugene commented on code/game/machinery/computer/station_alert.dm
> +		alarm_monitor.register_alarm(src, /atom/.proc/update_icon)
```suggestion
		alarm_monitor.register_alarm(src, /atom/.proc/update_icon) // SIERRA
```

2023-03-29 18:43 UTC, SuhEugene commented on code/modules/alarm/alarm.dm
> +	return contents.len ? get_z(contents[1]) : 0
```suggestion
	return length(contents) ? get_z(contents[1]) : 0
```

2023-03-29 18:44 UTC, SuhEugene commented on test/check-paths.sh
> +exactly 6 "uses of .len" '\.len\b' -P
```suggestion
exactly 5 "uses of .len" '\.len\b' -P
```

2023-03-31 20:18 UTC, SuhEugene approved these changes

2023-03-31 20:18 UTC, merged