Троллинг южика
SierraBay/SierraBay12 pull request #207
Opened 2023-03-29 19:03 UTC by ImJustKisik

Prikol

2023-04-01 18:34 UTC, SuhEugene requested changes

2023-04-01 18:34 UTC, SuhEugene commented on mods/bluespace_kitty/_bluespace_kitty.dme
> Ё##ный рот этого казино! Б##ть!
> Ты кто такой, с##а, чтоб это сделать?

Может документ по модам и говно, но я требую чтобы ты его прочитал и переписал этот файл нормально

2023-04-01 18:34 UTC, SuhEugene commented on mods/global_modpacks.dm
Какой бля глобал... NotLikeThis

2023-04-01 18:35 UTC, SuhEugene commented on mods/bluespace_kitty/bluespace_kitty.dm
> +		strike_back(user)
Используй `post_use_item`

2023-04-01 19:00 UTC, SuhEugene submitted a review, later dismissed

2023-04-01 19:00 UTC, SuhEugene commented on mods/bluespace_kitty/bluespace_kitty.dm
> +/mob/living/simple_animal/passive/cat/real_runtime/post_use_item(obj/item/O, mob/living/user)
Это не так работает...
Эта функция не возвращает значение...

2023-04-01 19:00 UTC, SuhEugene commented on mods/bluespace_kitty/bluespace_kitty.dm
> +/mob/living/simple_animal/passive/cat/real_runtime/post_use_item(obj/item/O, mob/living/user)
```dm
/mob/living/simple_animal/passive/cat/real_runtime/post_use_item(obj/item/tool, mob/user, interaction_handled)
	if (interaction_handled)
	// ...
```

2023-04-01 19:00 UTC, SuhEugene commented on mods/bluespace_kitty/_bluespace_kitty.dme
Попробуй ещё раз.

<details>
<summary>Подсказка</summary>

`#endif` должен быть в конце.

</details>

2023-04-01 19:01 UTC, ImJustKisik commented on mods/bluespace_kitty/_bluespace_kitty.dme
а нахер он в конце если больше ничего не дефайнится, голова

2023-04-01 19:05 UTC, SuhEugene commented on mods/bluespace_kitty/_bluespace_kitty.dme
Чтобы инклюды происходили только если модпак с таким же названием не задефайнен, очевидно же

2023-04-01 19:06 UTC, SuhEugene commented on mods/bluespace_kitty/_bluespace_kitty.dme
Ну и чтобы все моды были в едином стиле, описанном в файле `mods/README.md`

2023-04-01 20:29 UTC, ImJustKisik commented
Заебись внатуре четко

2023-04-06 17:19 UTC, Furrior approved these changes
Отличная идея, мерджи уже

2023-04-06 17:22 UTC, merged