Bugfix: wrong FPB alert
SierraBay/SierraBay12 pull request #209
Opened 2023-03-30 16:23 UTC by ImJustKisik

fixes: #161 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: ППТ больше не ощущают голода
/🆑
```

</details>

- [X] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [X] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [X] Я запускал сервер со своими изменениями локально и все протестировал.

2023-03-31 15:44 UTC, SuhEugene requested changes

2023-03-31 15:44 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/life.dm
> +					clear_alert("hydration")
Нет. Не надо путать игроков. Как оно было раньше (до алёртов), так оно и должно быть сейчас

```suggestion
				if(390 to 395)
					clear_alert("hydration")
				if(250 to 390)
					throw_alert("hydration", hydrated)
```

2023-03-31 15:44 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/life.dm
> +					clear_alert("nutrition")
Нет. Не надо путать игроков. Как оно было раньше (до алёртов), так оно и должно быть сейчас

```suggestion
				if(390 to 395)
					clear_alert("nutrition")
				if(250 to 390)
					throw_alert("nutrition", well_fed)
```

2023-03-31 15:44 UTC, SuhEugene commented on code/modules/projectiles/ammunition/bullets.dm
> +	spent_icon = "pshell-spent"
```suggestion
	// icon_state = "fshell" // BAY
	// spent_icon = "fshell-spent" // BAY
	icon_state = "pshell" // SIERRA
	spent_icon = "pshell-spent" // SIERRA
```

2023-03-31 15:44 UTC, SuhEugene commented on code/modules/projectiles/projectile.dm
Это бы на оффы закоммитить..........

2023-03-31 15:44 UTC, SuhEugene commented on code/controllers/subsystems/initialization/modpacks.dm
> +		. = "<hr><br><center><b><font size = 3>Список Модификаций</font></b></center><br><hr><br>"
Би рашн, нот американ
```suggestion
		. = "<hr><br><center><b><font size = 3>Список модификаций</font></b></center><br><hr><br>"
```

2023-03-31 15:44 UTC, SuhEugene commented on code/controllers/subsystems/initialization/modpacks.dm
> +		var/datum/browser/popup = new(mob, "modpacks_list", "Список Модификаций", 480, 580)
```suggestion
		var/datum/browser/popup = new(mob, "modpacks_list", "Список модификаций", 480, 580)
```

2023-03-31 15:44 UTC, SuhEugene commented on code/game/objects/structures/window.dm
> +		qdel(grab)
```suggestion
		qdel(grab) // SIERRA
```

2023-03-31 15:53 UTC, ImJustKisik commented on code/modules/mob/living/carbon/human/life.dm
> +					clear_alert("nutrition")
Всё так как и должно быть. Это сделано, чтобы большую часть времени на экране было пусто. Смысл алертов в том, чтобы оповещать об изменениях, а не быть постоянным индикатором

2023-03-31 21:41 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/life.dm
> +					clear_alert("nutrition")
В таком случае велл фед однозначно должен быть синего цвета. Это **очень** сильно путает.

Я понял о чём ты ведёшь речь, я только сейчас заметил что это всего от 390 до 395.
Но всё-равно неприятная такая дичь с зелёным индикатором...

2023-04-01 05:43 UTC, ImJustKisik commented on code/modules/mob/living/carbon/human/life.dm
> +					clear_alert("nutrition")
Поправил иконки

2023-04-01 14:52 UTC, SuhEugene approved these changes

2023-04-01 14:54 UTC, merged