DEV-SIERRA: Mech-by-Shegar mod
SierraBay/SierraBay12 pull request #2277
Opened 2024-06-02 08:05 UTC by AmShegars

Этот мод сильно углубляет и улучшает мехов. Подробнее в чейнжлоге.

### Чейнджлог
```yml
🆑ВашНикнейм
soundadd: Новые звуки для поднятия и отпускания для энергощита, его смерти, для смг меха и автошотгана
rscadd: Добавлен новый кастомизатор в карго, удалены все старые. Все камуфляжи теперь в одном кастомизаторе, круто-круто
rscadd: Фабрикатор мехов теперь кушает плассталь. Повышены цены компонентов меха, сильно, очень, добавлены требования и других материалов, добавлена в печать возможность печати мех-смг и боевых сенсоров
rscadd: Добавлен держатель интегралок и соответствующий корпус интегралок для этого держателя
rscadd: ЭМИ удар по меху переносится в энергощит меха, если тот включён. Энергощит теперь получает урон от ЭМИ-ударов, его спрайт меняется в зависимости от оставшегося ХП у энергощита, если урона щиту накидали до 0 или ниже, щит уйдёт на 50 секундную перезагрузку
rscadd: Перенёс стрейф для мехов. Пока лишь паучьим лапам, ибо, баланс
rscdel: Удалён мендер, механ передан 
rscadd: Теперь слипер меха автоматически проведёт ПМП пострадавшему, перевязки, артерии, переломы
rscadd: Перенесена фича топтания и тарана. Если кто-то кто меньше меха стоит на пути, мех сдвинет его и нанесёт ему урон. Если под ногами меха кто-то оказался в момент как он встаёт на этот турф, мех топчет его. Урон и присутствие возможности не топтать и не таранит зависит от типа ног. Паучьи и лёгкие лапы МОГУТ не топтать и не таранить, если у мехвода зелёный интент
rscadd: Самоанализ меха даёт более точную информацию
rscadd: Перенесена фича, если мех не запитан, у модулей соответсующий спрайт
rscadd: Добавлен альт-клик у модулей
rscadd: Углублена механика невозможности использования модулей, если выбили руки - не работают модули на руках, если выбили грудь - не работают модули на груди
rscadd: Углублена механика ударом лапой меха, можно открывать обесточенные шлюзы, аирлоки, разбитые бласты
rscadd: Перенесена пассажирка меха. Перетягивайте себя на закрытого меха, выбирайте слот - залезайте на меха и катайтесь! Для этого нужны две пустые руки и немного времени для залезания. Чтоб слезть с меха, прожмите RESIST. Если вы в качестве пилота хотите снять пассажиров, нажмите RESIST тоже. Пассажиров сбрасывает, когда в меха прилетает дальняя атака НЕ в лицо 
rscadd: Добавлены второстепенные системы в меха – GPS, SPEAK, PLTSCN
rscadd: Добавлен полноценный огнестрел мехам с возможностью перезарядки – пулемёт для Мерков, автошотган для ЕРТ, СМГ для рнд
imageadd: Модульно перенёс спрайты и иконки мехов на старые, ТГ-шные с инфинити
imageadd: Упрощён интерфейс меха, второстепенные кнопки перенесены в Отдельную кнопку menu
maptweak: Выдал ЭК актуаторов, паучьих лап, мачете меха. Робо получили кастомизатор
balance: Добавлена балансировочная фича, урон по меху в спину умножается в 1.3 раз
balance: Углублена система здоровья мехов (Тарков-система), теперь общее хп меха вычисляется по формуле – Сумма ХП всех частей + крепкость материала. Смерть меха произойдёт, когда общее хп меха станет = 0. Можете посмотреть общее ХП меха в самоанализе меха. Если урон приходит в уже выбитую конечность, урон распределяется во все остальные части меха и распределяется, умножаясь на опр коэффициент(зависит от разбитой части тела в которую прилетает урон)
balance: Добавлено влияние материала на физическую стойкость меха внешнему урону. 1)Как и сказано выше, ХП материала учавствует в формуле расчёта хп меха 2) Материал сопротивляется брут урону, может впитывать максимум 5 единиц урона за атаку 3) Материал сопротивляется бёрн урону, может впитывать максимум 5 единиц урона за атаку
balance: Мех слепнет не от урона по голове, а по отсутсвию камеры у головы меха.
balance: Добавлен ЕРТ и Мерк мех. Мерк мех доступен только после обьявления войны и в 1 штуке. ЕРТ мех доступен тогда, когда откроют гараж педали или обр откроют ионкой:3
balance: Подняты ХП конечностей меха. Поднята пулестойкость и лазеростойкость у ЭМИ брони
balance: атмос щит перенесён на плечо, ибо на спине ему делать нечего
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-06-02 08:41 UTC, UEDCommander requested changes

2024-06-02 08:41 UTC, UEDCommander commented on code/modules/mechs/mech_icon.dm
> +		new_overlays += back_passengers_overlays
```suggestion
		AddOverlays(back_passengers_overlays, new_overlays)
```

2024-06-02 08:41 UTC, UEDCommander commented on code/modules/mechs/mech_icon.dm
> +		new_overlays += left_back_passengers_overlays
```suggestion
		AddOverlays(left_back_passengers_overlays, new_overlays)
```

2024-06-02 08:41 UTC, UEDCommander commented on code/modules/mechs/mech_icon.dm
> +		new_overlays += right_back_passengers_overlays
```suggestion
		AddOverlays(right_back_passengers_overlays, new_overlays)
```

2024-06-02 08:41 UTC, UEDCommander commented on code/modules/mechs/mech_icon.dm
> +		new_overlays += right_back_passengers_overlays
И так далее во всех местах где к new_overlays что-то добавляется

2024-06-03 08:24 UTC, AmShegars commented
Пробовал применять эту подсистему - полное дерьмо, вылезают множественные аномалии поведения, ломаются блять совсем другие участки кода, от чего в код приходится ОБИЛЬНО СРАТЬ от чего он превращается в мусорку, и ради чего??? Я не буду заменять new_overlays += на AddOverlays и т.д. , это просто идиотизм ёпта

2024-06-03 19:44 UTC, UEDCommander approved these changes

2024-06-03 19:44 UTC, merged