Звуки падения тел локально и через Z уровни
SierraBay/SierraBay12 pull request #321
Opened 2023-04-08 18:50 UTC by cuddleandtea

Добавлены звуки падения тел для людей и таргетно для влажных тел скреллов в вариации четырех штук каждая. Звуки сбаланшены, протестированы и вкусны, как яблочный пирог только-только из печи.

**Ишью:**
close #195 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
soundadd: Звук падения карбонов 4 штуки
soundadd: Отдельный звук падения скреллов 4 штуки
soundadd: Звук падения тела через Z уровни 4 штуки (старосыровский)
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-04-08 19:10 UTC, cuddleandtea commented
Странно, а у меня запускается и траблов с кодом нет...

2023-04-17 11:33 UTC, SuhEugene requested changes

2023-04-17 11:33 UTC, SuhEugene commented on code/modules/multiz/movement.dm
> +	playsound(loc, pick(GLOB.smash_sound), 50, 1)
`get_sfx` используется не совсем верно
Ты специально прописывал
```dm
if ("smash_sound")
    // ...
```

Так что будет верным
```suggestion
	playsound(loc, "smash_sound", 50, 1)
```


Глянь `packs/sierra-tweaks/mob/bodyfall_sound.dm`, там ты сделал правильно

2023-04-24 14:47 UTC, cuddleandtea commented
Всё пофикшено, товарищи. Можно заливать

2023-04-24 14:59 UTC, cuddleandtea commented
Проверил ещё раз на локалке после апдейта. Всё работает.

2023-04-24 15:27 UTC, SuhEugene approved these changes

2023-04-25 17:07 UTC, SuhEugene commented
Замёржить, наверн, надо...

2023-04-25 17:08 UTC, merged