[MIRROR] `/mob` `New()` -> `Initialize()`
SierraBay/SierraBay12 pull request #385
Opened 2023-04-14 16:07 UTC by SierraHelper

# Оригинальный PR: Baystation12/Baystation12#33245
Passes through all cases of `/mob` subtypes overriding `New()` and replaces them with `Initialize()`, `LateInitialize()`, or type definitions as applicable.

## Changelog
:cl: SierraKomodo
refactor: Updated intialization for mobs.
/:cl:

## Other Changes
- Added `skip_timer` flag to `/mob/proc/equip_to_appropriate_slot()`, which causes the proc chain to skip the do_after timer call by passing directly through to `equip_to_slot_if_possible()` as `TRYEQUIP_INSTANT`.

2023-04-17 11:58 UTC, SuhEugene commented
Опять кривой чейнджлог...

2023-04-17 12:02 UTC, SuhEugene requested changes
Надо резомей и тоерб переписать + решить конфликты

2023-04-19 14:49 UTC, ImJustKisik approved these changes

2023-04-19 14:51 UTC, SuhEugene approved these changes
Наверное норм

2023-04-19 14:51 UTC, merged