feat: legalese language
SierraBay/SierraBay12 pull request #388
Opened 2023-04-14 22:44 UTC by Furrior

Возвращает канцеляризм как язык.

<details>
<summary>Чейнджлог</summary>

```yml
🆑Furior
rscadd: Снова добавлен канцеляризм как язык.
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-04-15 05:07 UTC, LordNest approved these changes
Sounds Legit
![image](https://user-images.githubusercontent.com/77477080/232184260-f4585de4-34a4-4b81-85a9-ea467cb44265.png)
Не забыть вырубить Восходу высокий уровень бюрократии, когда до этого дойдёт

2023-04-15 05:11 UTC, ImJustKisik requested changes
Так вейт, то-есть все живые существа вне зависимости от культуры и языка поставив себе мастера бюрократии - получают возможность общаться между собой? 
Не кажется ли, что это уже как-то слишком?

Можно ли сделать ограничение по профессиям или отрезать возможность говорить, оставив возможность только писать?

2023-04-17 12:07 UTC, SuhEugene reviewed
У меня есть плохое предчувствие...

2023-04-17 12:07 UTC, SuhEugene commented on mods/skills/bureaucracy/legalese_language/robot_module.dm
Мне что-то подсказывает что эта идея очень хуёва...
Через `New()` и присвоение не сработает?

2023-04-17 12:07 UTC, SuhEugene commented on mods/skills/bureaucracy/legalese_language/selenian.dm
Аналогично

2023-04-22 18:26 UTC, ImJustKisik approved these changes

2023-05-03 08:26 UTC, SuhEugene approved these changes

2023-05-03 08:27 UTC, SuhEugene commented
3 недели фичу ждали. Вот это скорость, вот это оперативность!!!

2023-05-03 08:27 UTC, merged