Jukebox and custom tapes fixes
SierraBay/SierraBay12 pull request #401
Opened 2023-04-16 17:18 UTC by cuddleandtea

Подробно указываю на все изменения в чейнджлоге и коммитах.

close #352 
close #353 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Джекбокс теперь принимает кассеты. Интерфейс настроен
soundadd: Новые звуки для поднимания и опускания кассет
soundadd: Новые звуки для вставления и вынимания кассет из джекбокса
tweak: Перезаписыватель теперь имеет правильный радиус взаимодействия
tweak: Зарядка принимает музыкальные плееры на перезарядку
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-04-16 22:17 UTC, cuddleandtea commented
Что-то  много ошибок в тестах вылезло. Надо было дождаться их окончания. Смотреть буду только уже в среду где косяки вышли

2023-04-17 06:22 UTC, LordNest approved these changes

2023-04-17 12:39 UTC, SuhEugene requested changes
Тык тык тык и будет просто идеально

2023-04-17 12:39 UTC, SuhEugene commented on code/game/machinery/jukebox.dm
> +	var/obj/item/music_tape/tape
```suggestion
	var/obj/item/music_tape/tape // SIERRA
```

2023-04-17 12:39 UTC, SuhEugene commented on code/game/machinery/jukebox.dm
> +/obj/machinery/jukebox/verb/eject()
```suggestion
// [SIERRA]
/obj/machinery/jukebox/verb/eject()
```

2023-04-17 12:39 UTC, SuhEugene commented on code/game/machinery/jukebox.dm
> +//[/SIERRA]
```suggestion
// [/SIERRA]
```

2023-04-17 12:39 UTC, SuhEugene commented on code/game/machinery/jukebox.dm
> +//[SIERRA]
```suggestion
// [SIERRA]
```

2023-04-17 12:39 UTC, SuhEugene commented on code/game/machinery/jukebox.dm
> +//[/SIERRA]
```suggestion
// [/SIERRA]
```

2023-04-17 12:42 UTC, SuhEugene requested changes
А если смотреть не на стиль кода, а в целом, то это надо делать сьеррабейский дубликат жукбокса

Нужен какой-то обж/стракча/жукбокс/тейп, у которого ты перепишешь приём тейпов
И его нужно именно в мод сунуть
Ошибки возникают как раз из-за того что модов нет на тестовых картах, а жукбокс тейпы просит

2023-04-24 14:54 UTC, cuddleandtea commented
А сейчас ошибок нет. Можно ли будет залить так или действительно делать новый полностью жубокс через мод со всеми составляющими? Просто мы везде заменяем стандартный жубокс на этот и смысла оставлять старый на сервере..

2023-05-06 19:10 UTC, cuddleandtea commented
Займусь этой дичью в отпуске и перенесу в мод

2023-05-08 13:51 UTC, cuddleandtea commented
Разбил на два разных ПРа. Этот кошмар закрываю

2023-05-08 13:51 UTC, closed without merging