FIX: white space
SierraBay/SierraBay12 pull request #610
Opened 2023-05-31 15:32 UTC by ImJustKisik

Никакого больше белого космоса 

<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Белый космос больше не является проблемой 
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-06-01 15:54 UTC, SuhEugene requested changes
Давай без спавнов, а?
Дилей тоже сработает, причём абсолютно так же

2023-06-02 12:07 UTC, ImJustKisik commented
> Давай без спавнов, а? Дилей тоже сработает, причём абсолютно так же

Какой ещё дилей

2023-06-02 21:02 UTC, SuhEugene commented
> > Давай без спавнов, а? Дилей тоже сработает, причём абсолютно так же
> 
> Какой ещё дилей

`delay(2 SECONDS)`
Или `sleep(2 SECONDS)`

Не помню как его звать точно, один из них

2023-06-02 21:02 UTC, SuhEugene commented
Тебе естессна надо просто `sleep(1)` (или `delay(1)`)

2023-06-03 14:40 UTC, ImJustKisik commented
> Тебе естессна надо просто `sleep(1)` (или `delay(1)`)

Процедуры delay() - в билде вообще не существует, а sleep: "delaying the entire procedure"

2023-06-03 18:49 UTC, SuhEugene commented
> > Тебе естессна надо просто `sleep(1)` (или `delay(1)`)
> 
> Процедуры delay() - в билде вообще не существует, а sleep: "delaying the entire procedure"

Ну дилеинг и дилеинг.
Оно в return выкидывает точку, а сам прок стопается. Всё по кайфам

2023-06-04 14:43 UTC, SuhEugene approved these changes

2023-06-04 14:43 UTC, merged