FIX: ETA timer now in sync with the subsystem movement speed
SierraBay/SierraBay12 pull request #622
Opened 2023-06-03 14:28 UTC by ImJustKisik

Title
<details>
<summary>Чейнджлог</summary>

```yml
🆑
bugfix: Чинит отображение скорости объектов на овермапе
/🆑
```

</details>

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-06-10 00:24 UTC, SuhEugene commented
Откуда 10? Откуда 7? Что за гениальности...

2023-06-10 07:56 UTC, ImJustKisik commented
> Откуда 10? Откуда 7? Что за гениальности...

```
/datum/controller/subsystem/processing/overmap
	name = "Overmap"
	priority = SS_PRIORITY_OVERMAP
	flags = SS_TICKER|SS_NO_INIT
	**wait = 7**
```

2023-06-11 19:15 UTC, SuhEugene commented on code/modules/overmap/ships/computers/helm.dm
> +			data["ETAnext"] = "[round(linked.ETA()/7)] seconds"
Может тогда стоило бы написать что-то вроде такого?
```suggestion
			data["ETAnext"] = "[round(linked.ETA()/SSovermap.wait)] seconds"
```

2023-06-11 19:16 UTC, SuhEugene requested changes
Долой магические числа

2023-08-28 05:14 UTC, merged