Add: Vintage RIG and Healthbar module
SierraBay/SierraBay12 pull request #7
Opened 2023-02-12 11:49 UTC by ImJustKisik

Port from DS13

🆑 
imageadd: "Implemented the Vintage rig, with sprites by Mr Mann. The vintage rig is an extremely bulky antique suit that significantly slows the user, but provides a ton of protection and a few useful modules. 
rscadd: "Added the healthbar rig module, which displays the user's health in a meter along their spine. The healthbar is standard equipment in all rigs."
/🆑

2023-02-14 17:57 UTC, SuhEugene submitted a review, later dismissed
Если убрать все неиспользуемые проки, то можно вполне засунуть абсолютно всё в модпак. Либо же оставить всё что связано с ношением предмета.
Но просчёт здоровья и подобную дичь в любом случае надо запихуивать в модпак

2023-02-14 17:57 UTC, SuhEugene commented on code/game/objects/items.dm
> +
Этот прок нигде не используется => не нужен

2023-02-14 17:57 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/inventory.dm
> +			update_inv_s_store(redraw_mob)
Так как прок update_wear_icon не нужен, при его удалении этот станет ненужным

2023-02-14 17:57 UTC, SuhEugene commented on code/game/objects/items.dm
> +		return (equip_slot != slot_none)
Прок не используется

2023-02-14 17:57 UTC, SuhEugene commented on code/game/objects/items.dm
> +		return slot_none
Эти проки тоже не используются

2023-02-15 03:57 UTC, ImJustKisik commented on code/game/objects/items.dm
> +
Забыл поменять holder.update_icon на  holder.update_wear_icon

2023-02-24 18:46 UTC, SuhEugene requested changes
Ыыыыыаыаыый. Мо- Моды. Моды! МОДЫ! МОООООДЫ!!!

Файл [`icons/mob/onmob/onmob_rig_modules.dmi`](https://github.com/SierraBay/SierraBay12/pull/7/files#diff-bbaff1dd05855e333dc141598108db928f2cf0e26d70d8a1e7593b652b867710) изменён!
Куча другого кор кода тронута!

2023-02-24 18:46 UTC, SuhEugene commented on code/__defines/items_clothing.dm
>  #define slot_wear_mask   2
Шоб как везде:
```suggestion
#define slot_none        0
#define slot_first       1
#define slot_back        1
#define slot_wear_mask   2
```

2023-02-24 18:46 UTC, SuhEugene commented on code/datums/observation/updatehealth.dm
> +	expected_type = /mob/living
Я более чем уверен, что это всё можно в мод запихуйнуть

Или даже лучше в `sierra-tweaks`

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/clothing/spacesuits/rig/rig.dm
>  	return 0
В мод. Оверврайтом. (То же самое, но без `/proc/`)
```dm
/obj/item/rig/update_offline()
	var/go_offline = (!istype(wearer) || loc != wearer || wearer.back != src || canremove || sealing || !cell || cell.charge <= 0)
	if(offline != go_offline)
		offline = go_offline
		update_wear_icon()
		return 1
	return 0
```

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/clothing/spacesuits/rig/rig.dm
> +
В мод

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	var/slot_before = equip_slot
Угадаешь куда?

_(Правильный ответ: В мод)_

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/clothing/spacesuits/rig/rig.dm
> +
В мод тоже

2023-02-24 18:46 UTC, SuhEugene commented on baystation12.dme
> +#include "code\datums\observation\updatehealth.dm"
Раз [`code/datums/observation/updatehealth.dm`](https://github.com/SierraBay/SierraBay12/pull/7/files#diff-9e37297469ed99136e056d870612509c5d03fc55c2225225b667c0bb48e6f395) можно в `sierra-tweaks`, то и это туда же

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/mob/living/living.dm
> +	GLOB.updatehealth_event.raise_event(src)
В `sierra-tweaks`
```dm
/mob/living/updatehealth()
	. = ..()
	GLOB.updatehealth_event.raise_event(src)
```

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/mob/living/living.dm
> +	return ((working_health / maxHealth) * 100)
В `sierra-tweaks`

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/inventory.dm
> +			update_inv_s_store(redraw_mob)
Я вот даже хрен знает что тут сказать... В `sierra-tweaks`?

В `sierra-tweaks`

2023-02-24 18:46 UTC, SuhEugene commented on code/game/objects/items.dm
> +
В `sierra-tweaks`

2023-02-24 18:46 UTC, SuhEugene commented on code/game/objects/items.dm
> +
В `sierra-tweaks`

2023-02-24 18:46 UTC, SuhEugene commented on code/game/objects/items.dm
> +	equip_slot = slot
В `sierra-tweaks`

2023-02-24 18:46 UTC, SuhEugene commented on code/game/objects/items.dm
> +
В `sierra-tweaks`

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/clothing/spacesuits/rig/modules/modules.dm
> +	return
В мод

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/human_damage.dm
> +
В `sierra-tweaks`.
```dm
/mob/living/carbon/human/updatehealth()
	GLOB.updatehealth_event.raise_event(src)
	. = ..()
```

2023-02-24 18:46 UTC, SuhEugene commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	return lowest
В `sierra-tweaks`

2023-02-24 19:02 UTC, ImJustKisik commented on code/datums/observation/updatehealth.dm
> +	expected_type = /mob/living
А вот и не угадал, это тут должно остаться

2023-02-24 19:02 UTC, ImJustKisik commented
> Ыыыыыаыаыый. Мо- Моды. Моды! МОДЫ! МОООООДЫ!!!
> 
> Файл [`icons/mob/onmob/onmob_rig_modules.dmi`](https://github.com/SierraBay/SierraBay12/pull/7/files#diff-bbaff1dd05855e333dc141598108db928f2cf0e26d70d8a1e7593b652b867710) изменён! Куча другого кор кода тронута!

Я хз как оверрайдить эти иконки

2023-02-24 19:08 UTC, SuhEugene commented
> Я хз как оверрайдить эти иконки

Да, щас посмотрел код - никак
Видимо, живём с конфликтами

![pepechilesad](https://user-images.githubusercontent.com/32931701/221269618-26249bfb-1c58-41eb-a7e1-ff42a58d0f1c.png)

2023-03-01 12:42 UTC, ImJustKisik commented
Из-за будущих конфликтов иконок - придётся отказаться, пока я не придумаю как оверрайднуть иконки

2023-03-01 12:42 UTC, closed without merging