Feat: Sensors rework
SierraBay/SierraBay12 pull request #73
Opened 2023-02-24 19:44 UTC by ImJustKisik

Перенос сенсоров с Небулы на наш замечательный SierraBay

<details>
<summary>Чейнджлог</summary>

```yml
🆑
tweak: Добавлена овермапа новая, красивая и стильная 
/🆑
```

</details>

- [ ] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [ ] Я запускал сервер со своими изменениями локально и все протестировал.

2023-02-26 11:51 UTC, SuhEugene requested changes
А также неясно зачем изменён [`icons/turf/space.dmi`](https://github.com/SierraBay/SierraBay12/pull/73/files#diff-3baddd6dd106b0ce988489f245cba40184f460d8c97b47d6c13c9d4b1afbfe27) на целых два байта

2023-02-26 11:51 UTC, SuhEugene commented on maps/sierra/sierra_overmap.dm
> +	color = "#a97faa"
Здесь был COLOR_PURPLE, зачем убирать?
```suggestion
	color = COLOR_PURPLE
```

2023-02-26 11:51 UTC, SuhEugene commented on code/modules/overmap/ships/computers/helm.dm
> +	LAZYREMOVE(GLOB.overmap_helm_computers, src)
Список `overmap_helm_computers` инициализируется, из него удаляются компы, но не добавляются в него

2023-02-26 11:51 UTC, SuhEugene commented on code/modules/overmap/overmap_object.dm
> +var/global/list/overmap_unknown_ids = list()
Оно нигде не используется. Зачем?

2023-02-26 11:57 UTC, ImJustKisik commented on maps/sierra/sierra_overmap.dm
> +	color = "#a97faa"
Потому что у Сьерры на Инфинити другой цвет

2023-02-26 12:05 UTC, SuhEugene commented
Ну а ещё конфликты решить надо

2023-02-26 12:06 UTC, SuhEugene commented
Я бы их решил, но с `code/modules/overmap/ships/computers/helm.dm` надо разбираться, нельзя бездумно его решить

2023-03-04 07:28 UTC, ImJustKisik commented on code/modules/overmap/overmap_object.dm
> +var/global/list/overmap_unknown_ids = list()
незачем

2023-03-04 07:28 UTC, ImJustKisik commented on code/modules/overmap/ships/computers/helm.dm
> +	LAZYREMOVE(GLOB.overmap_helm_computers, src)
Поправил, теперь всё вкусно

2023-03-04 12:34 UTC, SuhEugene requested changes

2023-03-04 12:34 UTC, SuhEugene commented on code/modules/overmap/sectors.dm
>  		update_known_connections(TRUE)
Что-то тут не так...

Вот так должно было быть, наверное:
```suggestion
	if(sector_flags & OVERMAP_SECTOR_KNOWN)
		for(var/obj/machinery/computer/ship/helm/H as anything in GLOB.overmap_helm_computers)
			update_known_connections(TRUE)
```

2023-03-05 15:33 UTC, SuhEugene approved these changes
Пиздец)

2023-03-05 15:40 UTC, ImJustKisik commented
> Пиздец)

Не апрувед, а загони кого-нибудь протестировать

2023-03-07 15:16 UTC, merged

2023-03-08 13:29 UTC, HaCsO commented
Тут видимо присутствуют все те же баги овермапа что и на другом билде, она обновляется только когда кто то пялит в сенсоры, но когда сенсоры включены и ты пялишь в условную консольку пилотирования она не обновляется