Вышли и зашли нормально (Colorful Cloth revert and EMS fixes)
SierraBay/SierraBay12 pull request #797
Opened 2023-07-31 11:52 UTC by LordNest

Немного поломали дерево коммитов потому что кто-то видимо не защитил бранч. Починили дерево как смогли. Пофиксили ряд багов. 

### Чейнджлог
```yml
🆑LordNest
bugfix: Убрал переусложнённую систему покраски для исключения конфликтов. Поправил некоторые пути объектов.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-08-03 14:21 UTC, SuhEugene requested changes
Не, в папку инфинити мы не добавляем ничего.
Постеры отдельным модом. Гравген следуя руководству по модуляризации в `_master_files`

2023-08-03 14:21 UTC, SuhEugene commented on packs/infinity/_pack.dm
No

2023-08-03 14:21 UTC, SuhEugene commented on packs/infinity/machinery/gravity_generator/areas.dm
No x2

2023-08-03 14:21 UTC, SuhEugene commented on packs/infinity/structures/signs_ss220.dm
ЫА

2023-08-03 15:32 UTC, LordNest commented on packs/infinity/machinery/gravity_generator/areas.dm
Это буквально финиковский генератор

2023-08-03 17:55 UTC, LordNest commented on packs/infinity/machinery/gravity_generator/areas.dm
Перенёс

2023-08-06 10:10 UTC, SuhEugene requested changes
Пездец, я бы себя убил за такой ревью

2023-08-06 10:10 UTC, SuhEugene commented on baystation12.dme
> +#include "mods\nyc_posters\_nyc_posters.dm"
Эт лишнее

2023-08-06 10:10 UTC, SuhEugene commented on maps/sierra/sierra.dm
> +	#include "../../mods/_master_files/gravity_generator/gravity_generator.dm"
Документацию по модам писал дебил. Мастер файлс в `baystation12.dme`, пожалуйста

2023-08-06 10:10 UTC, SuhEugene commented on maps/sierra/z2_sierra_deck2.dmm
> +/obj/structure/sign/poster/nyc/would_you_plant{
А знаешь почему я отказался от подтипа `/nyc/`? Потому что оно пиздец багует постеры - начинают появляться пустые. Придётся в кор код лезть чтобы исправить. Так что не, это надо вернуть как было.

2023-08-06 10:10 UTC, SuhEugene commented on mods/nyc_posters/code/nyc_posters.dm
Вообще не понял чо тут произошло. Половина `nyc`, половина нет. nowallspawn придётся убрать ибо поведение для этого не прописано и будут опять же пустые постеры...

2023-08-06 10:10 UTC, SuhEugene commented on nano/templates/gravgen.tmpl
Надо назвать его соответственно моду как-то... Там в самом верху папки как раз должны быть пара файлов

2023-08-06 10:10 UTC, SuhEugene commented on mods/nyc_posters/code/nyc_posters.dm
Наверное даже сам исправлю в свободную минутку...

2023-08-06 10:10 UTC, SuhEugene commented on mods/_master_files/gravity_generator/areas.dm
No.
Путь должен полностью совпадать... Представь что `_master_files` это папка `infinity`...
Да, это плохо и больно представлять, но ты представь.
И вот мы пишем: `mods/_master_files/code/modules/...`, `mods/_master_files/icons/...`

2023-08-06 10:10 UTC, SuhEugene commented on baystation12.dme
> +#include "mods\nyc_posters\_nyc_posters.dm"
А нет, не лишнее. Надо исключить отсюда и из сьерры, и добавить в глобал.

2023-08-06 10:10 UTC, SuhEugene commented on mods/_maps/farfleet/maps/farfleet-1.dmm
> -/obj/structure/sign/poster/nyc_doctor_griefsey{
Аналогично постеру выше

2023-08-06 10:10 UTC, SuhEugene commented on mods/_maps/farfleet/maps/farfleet-1.dmm
> +/obj/structure/sign/poster/nyc/krotovuha{
Аналогично постеру выше

2023-08-06 10:10 UTC, SuhEugene commented on mods/_maps/farfleet/maps/farfleet-2.dmm
> +/obj/structure/sign/poster/nyc/no_alcohol{
Аналогично постеру выше

2023-08-12 18:48 UTC, ImJustKisik commented
Поправь тесты и апрувну

2023-08-17 06:29 UTC, SuhEugene approved these changes
В целом, я больше ничего не нашёл к чему докопаться...

2023-08-17 13:53 UTC, ImJustKisik approved these changes

2023-08-17 16:51 UTC, merged