[MOD] Gliding - Smooth movement
SierraBay/SierraBay12 pull request #897
Opened 2023-08-28 19:56 UTC by SuhEugene

ПР добавляет мод на плавное движение. С грабами там чутка кринжа из-за совместимости в виде мода, но покатит в целом то, съедобно.

### Чейнджлог
```yml
🆑SuhEugene
rscadd: Добавил штуку, делающую движение плавным, на замену дёрганиям экрана оффов.
/🆑
```

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2023-08-28 21:54 UTC, ImJustKisik commented
Господи, зачем

2023-08-28 21:55 UTC, ImJustKisik commented
Сделай по человечески, без мода. Это невозможно будет в будущем читать нормально

2023-08-28 22:01 UTC, ImJustKisik requested changes
Демодуляризировать нахер

2023-08-29 20:22 UTC, ImJustKisik approved these changes

2023-08-30 13:05 UTC, LordNest approved these changes
Третья попытка в глайдинг. Когда-нибудь я начну тестировать ПРы нормально, но только не сегодня

2023-08-30 13:28 UTC, merged