Калик)): Кальянная сага
SierraBay/SierraBay12 pull request #97
Opened 2023-03-07 19:54 UTC by BTLegit

🆑
rscadd: Не спиздил, а перенёс калик со старого билда с небольшой очисткой кода и фиксом пары багов. 
/🆑

2023-03-07 20:11 UTC, SuhEugene requested changes
Ладно, я наревьювился, зовите Глиста

2023-03-07 20:11 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +	..()
У нас так не принято
```suggestion
/obj/item/hookah/use_tool(obj/item/tool, mob/user)
	if(isflamesource(tool) || is_hot(tool))
		var/text = matchmes
		if(istype(tool, /obj/item/flame/match))
			text = matchmes
		else if(istype(tool, /obj/item/flame/lighter/zippo))
			text = zippomes
		else if(istype(tool, /obj/item/flame/lighter))
			text = lightermes
		else if(isWelder(tool))
			text = weldermes
		else if(istype(tool, /obj/item/device/assembly/igniter))
			text = ignitermes
		else
			text = genericmes
		text = replacetext(text, "USER", "[user]")
		text = replacetext(text, "NAME", "[name]")
		text = replacetext(text, "FLAME", "[tool.name]")
		light(text)
		return TRUE

	else if(istype(tool, /obj/item/tube))
		var/obj/item/tube/T = tool
		if(T.parent != src)
			to_chat(user, SPAN_WARNING("This tube is not from this hookah."))
			return TRUE
		tubes.Add(T)
		user.unEquip(T, src)
		GLOB.moved_event.unregister(user, T, /obj/item/tube/proc/check_exited)
		to_chat(user, SPAN_INFO("You put the tube in hookah."))
		return TRUE

	else if(istype(tool, /obj/item/coal))
		var/obj/item/coal/M = tool
		if(smoketime + M.volume > maxsmoketime)
			to_chat(user, SPAN_WARNING("Hookah is already full of coal."))
			return TRUE
		qdel(M)
		smoketime += M.volume
		user.visible_message(SPAN_INFO("[user] adds some coal to the hookah."), SPAN_INFO("You added coal to the hookah."))
		return TRUE

	else if(istype(tool, /obj/item/reagent_containers/food/snacks/grown/dried_tobacco))
		if(tool.reagents)
			tool.reagents.trans_to_obj(src, tool.reagents.total_volume)
			user.unEquip(tool, src)
			user.visible_message(SPAN_INFO("[user] put tobacco in the hookah."), SPAN_INFO("You put tobacco in the hookah."))
			qdel(tool)
			return TRUE

	else if(istype(tool, /obj/item/storage/box/large/coal))
		var/obj/item/storage/box/large/coal/box = tool
		var/coals = round((maxsmoketime-smoketime)/500)
		if(!coals)
			return TRUE
		smoketime += 500*coals
		for(var/i in 1 to coals)
			qdel(box.contents[1])
		src.visible_message(SPAN_INFO("[user] puts [coals] coal in hookah"), SPAN_INFO("You put [coals] coal in hookah"))
		return TRUE

	else if(istype(tool, /obj/item/reagent_containers))
		var/obj/item/reagent_containers/container_obj = tool
		var/datum/reagents/container = container_obj.reagents
		if(!container_obj.is_open_container())
			return TRUE
		if(!container.has_reagent(liquid_type))
			to_chat(user, SPAN_WARNING("This liquid is not appropriate for use in hookahs."))
			return TRUE
		var/transfer_value = min(min(container.get_reagent_amount(liquid_type), container_obj.amount_per_transfer_from_this), max_liquid_level-liquid_level)
		if(transfer_value<=0)
			to_chat(user, SPAN_WARNING("You can't pour any more water in the hpokah."))
			return TRUE
		container.remove_reagent(liquid_type, transfer_value)
		liquid_level += transfer_value
		playsound(src.loc,'sound/effects/pour.ogg',50,-1)
		src.visible_message(SPAN_INFO("[user] filled a hookah from a [container_obj]."))
		update_icon()
		return TRUE
		
	return ..()
```

2023-03-07 20:11 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +			return 1
Как же хочется `TRUE` и `FALSE` вместо 1 и 0
```suggestion
			return TRUE
```

2023-03-07 20:11 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +		return 1
```suggestion
		return TRUE
```

2023-03-07 20:11 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +			return
```suggestion
			return FALSE
```

2023-03-07 20:11 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +		return
```suggestion
		return FALSE
```

2023-03-07 20:11 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +		playsound(src.loc, 'packs/infinity/sound/effects/hookah_lit.ogg',50, 0, -1)
Для красоты
```suggestion
	if(lit || !smoketime)
		return

	if(submerged())
		to_chat(usr, SPAN_WARNING("You cannot light \the [src] underwater."))
		return
		
	lit = TRUE
	damtype = "burn"
	var/turf/T = get_turf(src)
	T.visible_message(flavor_text)
	update_icon()
	START_PROCESSING(SSobj, src)
	set_scent_by_reagents(src)
	playsound(src.loc, 'packs/infinity/sound/effects/hookah_lit.ogg',50, 0, -1)
```

2023-03-07 20:41 UTC, SuhEugene requested changes

2023-03-07 20:41 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +	var/ignitermes = "<span class='info'>USER fiddles with FLAME, and manages to light NAME with the power of science.</span>"
Это всё надо в дефайны `SPAN_` завернуть
<details>
<summary>Подсказка</summary>

- `SPAN_INFO("текст")`
- `SPAN_CLASS('rose', "текст")`

</details>

2023-03-07 20:42 UTC, SuhEugene commented
Остальное точно на глиста оставляю

2023-03-07 22:22 UTC, ImJustKisik commented on packs/infinity/items/hookah.dm
> +	var/maxsmoketime = 5000
Указать количество не в тиках, а секундах 
5000 > 50 SECONDS

2023-03-07 23:54 UTC, SuhEugene commented on packs/infinity/items/hookah.dm
> +	var/maxsmoketime = 5000
500 же

2023-03-13 17:34 UTC, SuhEugene approved these changes
Проблем не вижу. @ImJustKisik твой выход.

2023-03-14 20:28 UTC, ImJustKisik commented on packs/infinity/items/hookah.dm
> +/obj/item/hookah/proc/light(flavor_text = "[usr] lights the [name].")
![Uploading image-54.png…]()

2023-03-14 20:28 UTC, ImJustKisik commented on packs/infinity/items/hookah.dm
> +/obj/item/hookah/proc/light(flavor_text = "[usr] lights the [name].")
![image-54](https://user-images.githubusercontent.com/87862013/225128693-b6d19a65-8cb9-483c-9e47-e3505dc933f3.png)

2023-03-26 14:26 UTC, merged